require('../dist/companies.js');require('../dist/boards.js');
const J=require('../dist/judge.js'),E=require('../dist/engine.js'),{test}=require('node:test'),assert=require('node:assert/strict');
function actionState(action,number=''){
 let s=E.reduce(E.initial(),{type:'setup',players:2,immigrant:'',market:[],confirmed:true});s=E.reduce(s,{type:'start'});s=E.reduce(s,{type:'card',number,order:['AW','PB','BGS','STR'],policies:['2','7'],bonus:''});
 for(let i=0;i<4;i++)s=E.reduce(s,{type:'check',confirmed:true,note:'test',movements:[]});s.actions={0:E.ACTIONS.filter(x=>x!==action),2:[action]};return s;
}
test('BGS confirmation transfers cash, stock, revenue, and purchased resources atomically',()=>{const s=actionState('BGS'),v=J.evaluateAction(s,'BGS');assert.equal(v.feasible,true);const n=E.reduce(s,{type:'action',first:'yes',plan:v.plan});assert.equal(n.records.personal.Working.values.cash,15);assert.equal(n.records.personal.Working.values.health,3);assert.equal(n.records.common.values.health,2);assert.equal(n.records.personal.State.values.cash,135);assert.equal(n.records.personal.Capitalist.values.revenue,120);});
test('BGS buys one population from a second affordable source after a single-source purchase',()=>{const s=actionState('BGS');s.records.personal.Working.values.cash=50;s.records.personal.Capitalist.values.health=3;s.records.personal.Capitalist.values.healthPrice=5;const v=J.evaluateAction(s,'BGS');assert.equal(v.feasible,true);assert.equal(v.plan.resource,'health');assert.equal(v.plan.qty,6);assert.deepEqual(v.plan.purchases.map(x=>[x.source,x.qty]),[['State',3],['Capitalist',3]]);const n=E.reduce(s,{type:'action',first:'yes',plan:v.plan});assert.equal(n.records.personal.Working.values.health,6);assert.equal(n.records.personal.Working.values.cash,20);assert.equal(n.records.common.values.health,2);assert.equal(n.records.personal.Capitalist.values.health,0);assert.equal(n.records.personal.Capitalist.values.revenue,135);});
test('foreign luxury purchase transfers its tariff to the State treasury',()=>{const s=actionState('BGS');s.records.common.values.health=0;s.records.common.values.education=0;s.records.personal.Capitalist.values.health=0;s.records.personal.Capitalist.values.education=0;s.records.personal.Capitalist.values.luxury=0;const v=J.evaluateAction(s,'BGS');assert.equal(v.plan.resource,'luxury');assert.equal(v.plan.purchases[0].stateTariff,9);const n=E.reduce(s,{type:'action',first:'yes',plan:v.plan});assert.equal(n.records.personal.Working.values.cash,3);assert.equal(n.records.personal.Working.values.luxury,3);assert.equal(n.records.personal.State.values.cash,129);});
test('State player receives public-service sale benefits',()=>{const s=actionState('BGS');s.records.participants.State='human';let v=J.evaluateAction(s,'BGS'),n=E.reduce(s,{type:'action',first:'yes',plan:v.plan});assert.equal(n.records.personal.State.values.vp,1);const free=actionState('BGS');free.records.participants.State='human';free.positions[4]='A';v=J.evaluateAction(free,'BGS');n=E.reduce(free,{type:'action',first:'yes',plan:v.plan});assert.equal(n.records.personal.State.values.workingLegitimacy,1);});
test('card 13 State payment takes a State loan before paying when necessary',()=>{const s=actionState('BGS','13');s.records.personal.State.values.cash=0;s.records.personal.State.values.loans=0;const v=J.evaluateAction(s,'BGS'),n=E.reduce(s,{type:'action',first:'yes',plan:v.plan});assert.equal(v.plan.bonusCash,8);assert.equal(n.records.personal.State.values.loans,1);assert.equal(n.records.personal.State.values.cash,57);assert.equal(n.records.personal.Working.values.cash,23);});
test('STR confirmation places strike tokens on both selected companies',()=>{const s=actionState('STR');s.records.personal.Working.unions.Food=true;s.records.personal.Working.unions.Luxury=true;const v=J.evaluateAction(s,'STR');assert.equal(v.feasible,true);const n=E.reduce(s,{type:'action',first:'yes',plan:v.plan,strExhausted:false});assert.deepEqual(v.plan.companyIds.map(id=>n.records.companies[id].strike),[true,true]);});
test('deterministic AW confirmation moves unemployed workers and commits them',()=>{const s=actionState('AW');s.records.common.unemployed.Working.Purple=2;const before=Object.values(s.records.common.unemployed.Working).reduce((a,b)=>a+b,0),v=J.evaluateAction(s,'AW');assert.equal(v.feasible,true);assert.equal(v.plan.allocations[0].companyId,'state_local_tv_init');const n=E.reduce(s,{type:'action',first:'yes',plan:v.plan}),after=Object.values(n.records.common.unemployed.Working).reduce((a,b)=>a+b,0);assert.equal(after,before-2);assert.equal(n.records.companies.state_local_tv_init.slots.every(x=>x.owner==='Working'&&x.committed),true);});
test('PB confirmation registers a visible pending proposal, consumes a marker, and sets priority aside',()=>{const s=actionState('PB'),v=J.evaluateAction(s,'PB');assert.equal(v.feasible,true);assert.equal(v.plan.proposals[0].immediate,false);const p=v.plan.proposals[0],n=E.reduce(s,{type:'action',first:'yes',plan:v.plan,policyReviewed:true});assert.equal(n.records.personal.Working.values.billMarkers,2);assert.equal(n.aside.policies[p.id],'bill:Working');assert.deepEqual(n.proposals[p.id],{proposer:'Working',from:p.from,target:p.target,round:1,turn:1});});
test('pending WCA bill resolves from the policy tab without moving on rejection',()=>{const s=actionState('PB'),v=J.evaluateAction(s,'PB'),p=v.plan.proposals[0],pending=E.reduce(s,{type:'action',first:'yes',plan:v.plan,policyReviewed:true}),rejected=E.reduce(pending,{type:'policy',id:p.id,position:p.target,result:'failed',proposer:'Working'});assert.equal(rejected.positions[p.id],p.from);assert.equal(rejected.records.personal.Working.values.billMarkers,3);assert.equal(rejected.proposals[p.id],undefined);assert.equal(rejected.aside.policies[p.id],'bill:resolved');});
test('pending WCA bill moves to its proposed position on passage',()=>{const s=actionState('PB'),v=J.evaluateAction(s,'PB'),p=v.plan.proposals[0],pending=E.reduce(s,{type:'action',first:'yes',plan:v.plan,policyReviewed:true}),passed=E.reduce(pending,{type:'policy',id:p.id,position:'C',result:'passed',proposer:'Working'});assert.equal(passed.positions[p.id],p.target);assert.equal(passed.records.personal.Working.values.billMarkers,3);assert.equal(passed.proposals[p.id],undefined);});
test('passed immediate vote uses the shared election flow and applies the policy',()=>{const s=actionState('PB','30');s.records.personal.Working.values.influence=3;const v=J.evaluateAction(s,'PB'),p=v.plan.proposals[0];assert.equal(p.immediate,true);let n=E.reduce(s,{type:'action',first:'yes',plan:v.plan,policyReviewed:true});assert.equal(n.phase,'election');assert.equal(n.election.step,'declare');assert.equal(n.records.personal.Working.values.influence,2);assert.equal(n.records.personal.Working.values.billMarkers,3);assert.equal(n.records.common.values.workingVotesOutside,15);n=E.reduce(n,{type:'electionDeclare',sides:{Working:'favor',Capitalist:'against'},cubes:{Working:4,Capitalist:1,Middle:0}});assert.equal(n.election.autoPlans.Working.type,'none');n=E.reduce(n,{type:'electionResolve',spends:{Capitalist:0},autoSymbols:{}});assert.equal(n.phase,'end');assert.equal(n.positions[p.id],p.target);assert.equal(n.records.personal.Working.values.vp,3);assert.equal(n.lastElection.passed,true);});
test('card 29 evaluates two proposals sequentially as Influence is spent and markers return',()=>{const s=actionState('PB','29');s.records.personal.Working.values.influence=3;s.records.personal.Working.values.billMarkers=1;const v=J.evaluateAction(s,'PB');assert.equal(v.plan.proposals.length,2);assert.deepEqual(v.plan.proposals.map(x=>x.immediate),[true,false]);v.plan.proposals[0].result='failed';const n=E.reduce(s,{type:'action',first:'yes',plan:v.plan,policyReviewed:true});assert.equal(n.records.personal.Working.values.influence,2);assert.equal(n.records.personal.Working.values.billMarkers,0);assert.equal(Object.keys(n.proposals).length,1);});
test('political pressure moves three outside cubes into the bag without moving priority cards',()=>{const s=actionState('AW'),before=E.copy(s.actions),n=E.reduce(s,{type:'action',first:'no',second:'no',plan:{action:'PRESSURE'}});assert.equal(n.records.common.values.workingVotesOutside,14);assert.deepEqual(n.actions,before);});
test('demonstration action records and removal clears the physical token',()=>{const s=actionState('DEM');s.records.common.unemployed.Working.Gray=20;const v=J.evaluateAction(s,'DEM');assert.equal(v.feasible,true);let n=E.reduce(s,{type:'action',first:'yes',plan:v.plan});assert.equal(n.records.common.tokens.demonstration,true);assert.equal(n.aside.actions.DEM,'demonstration');n=E.reduce(n,{type:'demReturn'});assert.equal(n.records.common.tokens.demonstration,false);assert.equal(n.aside.actions.DEM,undefined);});
test('production demonstration resolution updates Influence, opponent VP, token, and priority together',()=>{const s=actionState('DEM');s.records.common.unemployed.Working.Gray=20;s.records.personal.Working.unions.Food=true;s.records.personal.Capitalist.values.vp=20;const v=J.evaluateAction(s,'DEM');let n=E.reduce(s,{type:'action',first:'yes',plan:v.plan}),before=n.records.personal.Working.values.influence;n=E.reduce(n,{type:'demResolve'});assert.equal(n.records.personal.Working.values.influence,before+1);assert.equal(n.records.personal.Capitalist.values.vp,12);assert.equal(n.records.common.tokens.demonstration,false);assert.equal(n.aside.actions.DEM,undefined);});
test('demonstration is legal when unemployed workers exceed available slots by exactly two',()=>{const s=actionState('DEM'),status=WCARecords.demonstrationStatus(s.records);for(const skill of Object.keys(s.records.common.unemployed.Working))s.records.common.unemployed.Working[skill]=0;s.records.common.unemployed.Working.Gray=status.slots+2;const v=J.evaluateAction(s,'DEM');assert.equal(v.feasible,true);});
test('turn start automatically pays every affordable Working Class loan',()=>{let s=E.reduce(E.initial(),{type:'setup',players:2,immigrant:'',market:[],confirmed:true});s.records.personal.Working.values.cash=120;s.records.personal.Working.values.loans=3;s=E.reduce(s,{type:'start'});assert.equal(s.records.personal.Working.values.cash,20);assert.equal(s.records.personal.Working.values.loans,1);});
test('building and staffing a company removes an obsolete demonstration token and returns DEM',()=>{let s=actionState('DEM');const status=WCARecords.demonstrationStatus(s.records);for(const skill of Object.keys(s.records.common.unemployed.Working))s.records.common.unemployed.Working[skill]=0;s.records.common.unemployed.Working.Gray=status.slots+2;let v=J.evaluateAction(s,'DEM');s=E.reduce(s,{type:'action',first:'yes',plan:v.plan});const def=WCA_COMPANIES.find(d=>s.records.companies[d.id].status==='unbuilt'&&d.workers.length===2&&d.workers.every(x=>x.type!=='MiddleClass')),common=E.copy(s.records.common);common.unemployed.Working.Gray-=2;const value={status:'built',wage:'L2',operating:'yes',machinery:false,strike:false,note:'',slots:def.workers.map(()=>({owner:'Working',skill:'Gray',committed:true}))};s=E.reduce(s,{type:'record',section:'establish',id:def.id,value,common});assert.equal(s.records.common.tokens.demonstration,false);assert.equal(s.aside.actions.DEM,undefined);assert.equal(E.locate(s,'actions','DEM'),0);});
test('fiscal policy expansion buys and reveals the next public row, taking mandatory State loans',()=>{let s=E.reduce(E.initial(),{type:'setup',players:2,immigrant:'',market:[],confirmed:true});s.records.personal.State.values.cash=10;s=E.reduce(s,{type:'policy',id:'1',position:'B',result:'position',proposer:'other'});assert.equal(s.records.personal.State.values.cash,0);assert.equal(s.records.personal.State.values.loans,1);assert.equal(['state_public_university_pool','state_local_tv_pool','state_public_hospital_pool'].every(id=>s.records.companies[id].status==='built'),true);});
test('fiscal policy contraction closes the bottom public row, refunds State, and returns workers',()=>{let s=E.reduce(E.initial(),{type:'setup',players:2,immigrant:'',market:[],confirmed:true});s=E.reduce(s,{type:'policy',id:'1',position:'B',result:'position',proposer:'other'});const id='state_public_university_pool';s.records.companies[id].slots[0]={owner:'Working',skill:'Orange',committed:true};s.records.companies[id].operating='yes';const cash=s.records.personal.State.values.cash,workers=s.records.common.unemployed.Working.Orange;s=E.reduce(s,{type:'policy',id:'1',position:'C',result:'position',proposer:'other'});assert.equal(s.records.companies[id].status,'unbuilt');assert.equal(s.records.personal.State.values.cash,cash+60);assert.equal(s.records.common.unemployed.Working.Orange,workers+1);});
test('labor policy raises illegal wages without committing workers and keeps absent State companies at the policy minimum',()=>{let s=E.reduce(E.initial(),{type:'setup',players:2,immigrant:'',market:[],confirmed:true});s.records.companies.cc_supermarket_init.wage='L2';s=E.reduce(s,{type:'policy',id:'2',position:'A',result:'position',proposer:'other'});assert.equal(s.records.companies.cc_supermarket_init.wage,'L3');assert.equal(s.records.companies.cc_supermarket_init.slots.every(x=>!x.committed),true);assert.equal(s.records.companies.state_public_hospital_init.wage,'L3');s=E.reduce(s,{type:'policy',id:'2',position:'C',result:'position',proposer:'other'});assert.equal(s.records.companies.cc_supermarket_init.wage,'L3');assert.equal(s.records.companies.state_public_hospital_init.wage,'L1');});

