require('../dist/companies.js');require('../dist/boards.js');require('../dist/action-card-data.js');require('../dist/player-cards.js');
const E=require('../dist/engine.js'),{test}=require('node:test'),assert=require('node:assert/strict');
function player(){const s=E.reduce(E.initial(),{type:'setup',players:2,automaClass:'Working',confirmed:true,managePlayerCards:true});s.phase='player';return s;}
const free=(s,plan)=>E.reduce(s,{type:'capitalistFree',plan});
test('Prices use printed markers and free actions preserve hand before and after main action',()=>{let s=player();const cards=structuredClone(s.playerCards);s=free(s,{action:'PRICE',resource:'food',price:15});assert.equal(s.records.personal.Capitalist.values.foodPrice,15);assert.deepEqual(s.playerCards,cards);s.playerCards.used=true;const used=structuredClone(s.playerCards);assert.throws(()=>free(s,{action:'PRICE',resource:'health',price:8}),/使用済み/);s.records=WCARecords.applyCapitalistFree(s.records,{action:'PRICE',resource:'health',price:8},s.positions);assert.deepEqual(s.playerCards,used);assert.throws(()=>free(s,{action:'PRICE',resource:'food',price:10}),/販売価格/);s.phase='start';assert.throws(()=>free(s,{action:'PRICE',resource:'food',price:9}),/手番/);});
test('Wages can fall only without committed workers and must respect minimum',()=>{let s=player();s.positions['2']='C';s=free(s,{action:'WAGE',id:'cc_supermarket_init',wage:'L1'});assert.equal(s.records.companies.cc_supermarket_init.wage,'L1');assert.equal(s.records.companies.cc_supermarket_init.slots.some(x=>x.committed),false);assert.throws(()=>free(s,{action:'WAGE',id:'cc_supermarket_init',wage:'L3'}),/使用済み/);s.records=WCARecords.applyCapitalistFree(s.records,{action:'WAGE',id:'cc_supermarket_init',wage:'L3'},s.positions);assert.equal(s.records.companies.cc_supermarket_init.slots.every(x=>x.committed),true);assert.throws(()=>free(s,{action:'WAGE',id:'cc_supermarket_init',wage:'L2'}),/誓約/);s=player();assert.throws(()=>free(s,{action:'WAGE',id:'cc_supermarket_init',wage:'L1'}),/最低賃金/);});
test('Bonus pays employee class, uses revenue then capital and commits workers',()=>{let s=player(),v=s.records.personal.Capitalist.values,w=s.records.personal.Working.values.cash;v.revenue=2;v.capital=3;s=free(s,{action:'BONUS',id:'cc_supermarket_init'});assert.equal(s.records.personal.Working.values.cash,w+5);assert.equal(s.records.personal.Capitalist.values.revenue,0);assert.equal(s.records.personal.Capitalist.values.capital,0);assert.equal(s.records.companies.cc_supermarket_init.slots.every(x=>x.committed),true);assert.throws(()=>free(s,{action:'BONUS',id:'cc_supermarket_init'}),/不足/);assert.throws(()=>free(s,{action:'BONUS',id:'sc_hospital'}),/操業中/);});
test('Storage doubles capacity once, cannot borrow and rejected payment is atomic',()=>{let s=player(),before=WCARecords.capitalistStorageRoom(s.records.personal.Capitalist.values,'food');s=free(s,{action:'STORAGE',resource:'food'});assert.equal(WCARecords.capitalistStorageRoom(s.records.personal.Capitalist.values,'food'),before+8);assert.throws(()=>free(s,{action:'STORAGE',resource:'food'}),/購入済み/);s.records.personal.Capitalist.values.revenue=19;s.records.personal.Capitalist.values.capital=0;const copy=structuredClone(s);assert.throws(()=>free(s,{action:'STORAGE',resource:'health'}),/不足/);assert.deepEqual(s,copy);});
test('Loan repayment uses only capital and cannot substitute revenue or create a loan',()=>{let s=player(),v=s.records.personal.Capitalist.values;v.loans=2;v.capital=49;v.revenue=100;assert.throws(()=>free(s,{action:'LOAN'}),/資本50/);v.capital=50;s=free(s,{action:'LOAN'});v=s.records.personal.Capitalist.values;assert.equal(v.loans,1);assert.equal(v.capital,0);assert.equal(v.revenue,100);v.loans=0;assert.throws(()=>free(s,{action:'LOAN'}),/ありません/);});
