require('../dist/companies.js');require('../dist/boards.js');require('../dist/judge.js');require('../dist/capitalist.js');
const E=require('../dist/engine.js'),{test}=require('node:test'),assert=require('node:assert/strict');
function setup(deck=['29','5','7','9','20','21']){return E.reduce(E.initial(),{type:'setup',players:2,immigrant:'',market:[],automaClass:'Capitalist',deck,confirmed:true});}
test('Capitalist automa setup swaps participants and uses official priority layout',()=>{const s=setup();assert.equal(s.automaClass,'Capitalist');assert.deepEqual(s.records.participants,{Working:'human',Capitalist:'automa',Middle:'absent',State:'absent'});assert.deepEqual(s.actions,{0:['SA','LOB','SC'],1:['BC','SFM','PB']});assert.deepEqual(s.policies,{0:['2','4','6','7'],1:['3']});assert.deepEqual(s.aside.policies,{1:'initial',5:'initial'});assert.deepEqual(s.aiDeck,['29','5','7','9','20','21']);});
test('Capitalist card is drawn from the registered six-card deck',()=>{let s=setup();s=E.reduce(s,{type:'start'});assert.equal(s.phase,'checks');assert.equal(s.card.number,'29');assert.deepEqual(s.card.order,['PB','BC','SFM','LOB']);assert.deepEqual(s.card.policies,['6','3']);});
test('Capitalist policy check moves PB and matching policy cards',()=>{const s=setup();s.card={number:'29',...CCAJudge.CARD_DATA['29']};const v=CCAJudge.evaluate(s,'PB');assert.equal(v.status,'ready');assert(v.movements.some(x=>x.series==='actions'&&x.card==='PB'));assert(v.movements.some(x=>x.series==='policies'&&x.card==='6'));assert(v.movements.some(x=>x.series==='policies'&&x.card==='3'));});
test('Capitalist export and influence checks ask only for missing board facts',()=>{const s=setup();s.card={number:'21',...CCAJudge.CARD_DATA['21']};let v=CCAJudge.evaluate(s,'SFM');assert.deepEqual(v.questions.map(x=>x.id),['exportTransactions']);v=CCAJudge.evaluate(s,'SFM',{exportTransactions:1});assert.equal(v.movements[0].card,'SFM');assert.equal(v.movements[0].up,2);s.proposals['2']={proposer:'Working',from:'B',target:'A'};v=CCAJudge.evaluate(s,'LOB');assert.deepEqual(v.questions.map(x=>x.id),['capitalistFutureInfluence','otherFutureInfluence']);});
test('Capitalist action confirmation hands the same turn to the Working player',()=>{let s=setup();s.phase='action';s.card={number:'29',...CCAJudge.CARD_DATA['29']};s=E.reduce(s,{type:'action',first:'yes',confirmed:true});assert.equal(s.phase,'player');assert.equal(s.turn,1);s=E.reduce(s,{type:'playerEnd'});assert.equal(s.phase,'start');assert.equal(s.turn,2);});
test('a registered Capitalist card completes all four checks in printed order',()=>{let s=setup(['29','5','7','9','20','21']);s=E.reduce(s,{type:'start'});for(const check of s.card.order){const answers=check==='SFM'?{exportTransactions:2}:check==='LOB'?{}:{},v=CCAJudge.evaluate(s,check,answers);assert.equal(v.status,'ready');s=E.reduce(s,{type:'check',confirmed:true,note:v.reasons.join('\n')||'移動なし',movements:v.movements});}assert.equal(s.phase,'action');assert.equal(s.index,4);assert(E.rank(s,'actions').includes('PB'));});
