require('../dist/companies.js');require('../dist/boards.js');
const J=require('../dist/judge.js'),E=require('../dist/engine.js'),{test}=require('node:test'),assert=require('node:assert/strict');

function setupCard(number){const c=J.CARD_DATA[String(number)];let s=E.reduce(E.initial(),{type:'setup',players:2,immigrant:'',market:[],confirmed:true});s.phase='action';s.card={number:String(number),order:[...c.order],policies:c.policies.map(String),bonus:c.bonus};return s;}

test('the attached catalog registers all thirty card rows',()=>{assert.deepEqual(Object.keys(J.CARD_DATA).map(Number).sort((a,b)=>a-b),Array.from({length:30},(_,i)=>i+1));for(const c of Object.values(J.CARD_DATA)){assert.equal(c.order.length,4);assert.equal(c.policies.length,2);assert(c.bonus);assert(c.bonusType);assert(c.special);assert(c.specialType);}});

test('card 6 always requests a free immediate vote, even with no marker or voting advantage',()=>{const s=setupCard(6);s.records.personal.Working.values.influence=0;s.records.personal.Capitalist.values.influence=5;s.records.personal.Working.values.billMarkers=0;s.records.common.values.workingVotesOutside=24;s.records.common.values.capitalistVotesOutside=17;const check=J.evaluate(s,'PB');assert.equal(check.movements.some(x=>x.card==='PB'),true);const v=J.evaluateAction(s,'PB');assert.equal(v.feasible,true);assert.equal(v.plan.proposals[0].immediate,true);assert.equal(v.plan.proposals[0].immediateCost,0);assert.match(v.reasons.join('\n'),/カード#6のボーナス/);const before=s.records.personal.Working.values.influence,n=WCARecords.applyAction(s.records,v.plan);assert.equal(n.personal.Working.values.influence,before);});

test('cards 6 and 19 pay Capitalist 20 and award 5 VP only when affordable',()=>{for(const number of [6,19]){const s=setupCard(number),v=J.evaluateAction(s,'SA'),before=s.records.personal.Capitalist.values.revenue;assert.equal(v.feasible,true);const n=WCARecords.applyAction(s.records,v.plan);assert.equal(n.personal.Working.values.cash,10);assert.equal(n.personal.Working.values.vp,5);assert.equal(n.personal.Capitalist.values.revenue,before+20);s.records.personal.Working.values.cash=19;assert.equal(J.evaluateAction(s,'SA').feasible,false);}});

test('card 13 makes the sole opponent pay 15 to Working Class',()=>{const s=setupCard(13),v=J.evaluateAction(s,'SA'),before=s.records.personal.Capitalist.values.revenue;assert.equal(v.feasible,true);assert.equal(v.plan.payer,'Capitalist');const n=WCARecords.applyAction(s.records,v.plan);assert.equal(n.personal.Working.values.cash,45);assert.equal(n.personal.Capitalist.values.revenue,before-15);});

test('cards 16 and 30 buy available Influence and replace every missing one with two bag cubes',()=>{for(const number of [16,30]){const s=setupCard(number);s.records.personal.Working.values.cash=7;s.records.common.values.influence=2;const v=J.evaluateAction(s,'SA');assert.equal(v.plan.buy,1);const n=WCARecords.applyAction(s.records,v.plan);assert.equal(n.personal.Working.values.cash,2);assert.equal(n.personal.Working.values.influence,2);assert.equal(n.records?.dummy,undefined);assert.equal(n.common.values.influence,1);assert.equal(n.common.values.workingVotesOutside,13);assert.equal(n.personal.State.values.cash,125);}});

test('card 22 removes two unemployed workers, prefers gray, recalculates population, and gains 10',()=>{const s=setupCard(22);s.records.common.unemployed.Working={Gray:1,Green:3,Blue:0,White:0,Orange:0,Purple:0};const v=J.evaluateAction(s,'SA');assert.equal(v.feasible,true);const n=WCARecords.applyAction(s.records,v.plan),left=Object.values(n.common.unemployed.Working).reduce((a,b)=>a+b,0);assert.equal(left,2);assert.equal(n.common.unemployed.Working.Gray,0);assert.equal(n.personal.Working.values.cash,40);assert.equal(n.personal.Working.values.workerCount,10);assert.equal(n.personal.Working.values.population,3);assert.equal(v.plan.removedSkills.length,2);});

test('card 16 bonus produces only eligible public Health companies and pays their wages before buying',()=>{const s=setupCard(16),beforeCash=s.records.personal.Working.values.cash,beforeEducation=s.records.common.values.education,beforeHealth=s.records.common.values.health,result=WCARecords.applyPublicCompanyBonus(s.records,'Health');assert.equal(result.preview.items.length,1);assert.equal(result.preview.wages,20);assert.equal(result.records.personal.Working.values.cash,beforeCash+20);assert.equal(result.records.common.values.education,beforeEducation);assert.equal(result.records.common.values.health,beforeHealth+4);const v=J.evaluateAction(s,'BGS');assert.equal(v.feasible,true);assert.equal(v.plan.publicProduction,true);assert.equal(v.plan.publicProductionIndustry,'Health');});

test('card 22 applies the same employed-worker payment bonus as card 13',()=>{const s=setupCard(22),v=J.evaluateAction(s,'BGS');assert.equal(v.feasible,true);assert(v.plan.bonusCash>0);const before=s.records.personal.State.values.cash,n=WCARecords.applyAction(s.records,v.plan);assert.equal(n.personal.State.values.cash>=before-v.plan.bonusCash,true);});

test('card 19 policy 2B assigns only unemployed workers and commits every new assignment',()=>{const s=setupCard(19);s.positions[2]='B';s.records.common.unemployed.Working={Gray:1,Green:0,Blue:0,White:1,Orange:0,Purple:0};const before=structuredClone(s.records.companies.cc_supermarket_init.slots),v=J.evaluateAction(s,'AW');assert.equal(v.feasible,true);assert(v.plan.reassignment);const n=WCARecords.applyAction(s.records,v.plan);assert.deepEqual(n.companies.cc_supermarket_init.slots,before);assert(n.companies.cc_clinic_init.slots.every(x=>x.owner==='Working'&&x.committed));assert.equal(Object.values(n.common.unemployed.Working).reduce((a,b)=>a+b,0),0);});

test('card 19 policy 2C may move uncommitted employees but never moves a committed worker',()=>{const s=setupCard(19);s.positions[2]='C';s.records.common.unemployed.Working={Gray:2,Green:0,Blue:0,White:0,Orange:0,Purple:0};const protectedSlot=structuredClone(s.records.companies.cc_supermarket_init.slots[0]);s.records.companies.cc_supermarket_init.slots[0].committed=true;const total=x=>Object.values(x.common.unemployed.Working).reduce((a,b)=>a+b,0)+Object.values(x.companies).reduce((a,c)=>a+c.slots.filter(y=>y.owner==='Working').length,0)+Object.values(x.personal.Working.unions).filter(Boolean).length,before=total(s.records),v=J.evaluateAction(s,'AW');assert.equal(v.feasible,true);assert(v.plan.reassignment);const n=WCARecords.applyAction(s.records,v.plan);assert.equal(total(n),before);assert.deepEqual(n.companies.cc_supermarket_init.slots[0],{...protectedSlot,committed:true});for(const c of Object.values(n.companies).filter(c=>c.status==='built'))assert(c.slots.every(x=>x.owner==='Working')||c.slots.every(x=>x.owner==='empty')||c.slots.some(x=>x.committed));});

test('card 19 stops when policy 2C has no legal move because all employees are committed',()=>{const s=setupCard(19);s.positions[2]='C';s.records.common.unemployed.Working={Gray:2,Green:0,Blue:0,White:0,Orange:0,Purple:0};for(const c of Object.values(s.records.companies))for(const slot of c.slots)if(slot.owner==='Working')slot.committed=true;const v=J.evaluateAction(s,'AW');assert.equal(v.feasible,false);});

test('card 19 never delegates a large two-player search back to the player',()=>{const source=require('node:fs').readFileSync(require('node:path').resolve(__dirname,'../dist/judge.js'),'utf8');assert.doesNotMatch(source,/合法な配置案が多すぎる/);});

test('the three vote-cube special action families update the visible outside counts',()=>{let s=setupCard(4),before=s.records.common.values.workingVotesOutside,v=J.evaluateAction(s,'SA'),n=WCARecords.applyAction(s.records,v.plan);assert.equal(n.common.values.workingVotesOutside,before-s.records.personal.Working.values.population);s=setupCard(1);v=J.evaluateAction(s,'SA');v.plan.drawn={Capitalist:2,Middle:1};n=WCARecords.applyAction(s.records,v.plan);assert.equal(n.common.values.workingVotesOutside,s.records.common.values.workingVotesOutside-3);assert.equal(n.common.values.capitalistVotesOutside,s.records.common.values.capitalistVotesOutside+2);assert.equal(n.common.values.middleVotesOutside,s.records.common.values.middleVotesOutside+1);s=setupCard(3);v=J.evaluateAction(s,'SA');v.plan.drawn={Working:2,Capitalist:3,Middle:1};n=WCARecords.applyAction(s.records,v.plan);assert.equal(n.common.values.workingVotesOutside,s.records.common.values.workingVotesOutside);assert.equal(n.common.values.capitalistVotesOutside,s.records.common.values.capitalistVotesOutside+3);assert.equal(n.common.values.middleVotesOutside,s.records.common.values.middleVotesOutside+1);});

test('cards 17, 24, and 11 apply free immediate vote, two proposals, and desired-section proposal',()=>{let s=setupCard(17);s.records.personal.Working.values.influence=2;s.records.personal.Capitalist.values.influence=1;let v=J.evaluateAction(s,'PB');assert.equal(v.plan.proposals[0].immediateCost,0);s=setupCard(24);s.records.personal.Working.values.billMarkers=2;v=J.evaluateAction(s,'PB');assert.equal(v.plan.proposals.length,2);s=setupCard(11);s.positions[1]='C';s.positions[2]='C';s.positions[6]='C';v=J.evaluateAction(s,'PB');assert.equal(v.plan.proposals[0].target,'A');assert.equal(v.plan.proposals[0].immediate,false);});

test('education discount and luxury subsidy change the actual payer while preserving seller revenue',()=>{let s=setupCard(4),w=s.records.personal.Working.values;w.health=w.population;w.luxury=w.population;w.education=0;w.cash=30;s.positions[5]='C';s.records.common.values.health=0;s.records.personal.Capitalist.values.health=0;s.records.personal.Capitalist.values.education=0;let v=J.evaluateAction(s,'BGS');assert.equal(v.plan.resource,'education');assert.equal(v.plan.workerCost,v.plan.qty*5);s=setupCard(15);w=s.records.personal.Working.values;w.health=w.population;w.education=w.population;w.luxury=0;w.cash=30;s.positions[1]='A';s.positions[6]='A';s.records.common.values.health=0;s.records.common.values.education=0;s.records.personal.Capitalist.values.health=0;s.records.personal.Capitalist.values.education=0;const cap=s.records.personal.Capitalist.values;cap.luxury=5;cap.luxuryPrice=7;v=J.evaluateAction(s,'BGS');assert.equal(v.plan.cost,21);assert.equal(v.plan.workerCost,11);assert.equal(v.plan.stateSubsidy,10);const capBefore=cap.revenue,stateBefore=s.records.personal.State.values.cash,n=WCARecords.applyAction(s.records,v.plan);assert.equal(n.personal.Working.values.cash,19);assert.equal(n.personal.Capitalist.values.revenue,capBefore+21);assert.equal(n.personal.State.values.cash,stateBefore-10);});

test('public-only purchase pays five per unemployed worker and excludes private sellers',()=>{const s=setupCard(3),w=s.records.personal.Working.values;w.health=0;w.education=w.population;w.luxury=w.population;w.cash=0;s.positions[4]='B';s.records.common.unemployed.Working={Gray:3,Green:0,Blue:0,White:0,Orange:0,Purple:0};const v=J.evaluateAction(s,'BGS');assert.equal(v.feasible,true);assert.equal(v.plan.bonusCash,15);assert(v.plan.purchases.every(x=>x.source==='State'));});

test('worker bonuses gain a skilled worker, build a cooperative farm, and collect owner payments',()=>{let s=setupCard(7);s.positions[7]='B';s.records.common.unemployed.Working={Gray:1,Green:0,Blue:0,White:0,Orange:0,Purple:0};let v=J.evaluateAction(s,'AW');assert(v.plan.gainedSkill);assert(v.plan.allocations.every(a=>a.slots.length===s.records.companies[a.companyId].slots.length));let before=s.records.personal.Working.values.workerCount,n=WCARecords.applyAction(s.records,v.plan);assert.equal(n.personal.Working.values.workerCount,before+1);for(const a of v.plan.allocations)assert(n.companies[a.companyId].slots.every(x=>x.owner==='Working'&&x.committed));s=setupCard(2);s.records.common.unemployed.Working={Gray:3,Green:0,Blue:0,White:0,Orange:0,Purple:0};v=J.evaluateAction(s,'AW');assert(v.plan.buildCompanyId);n=WCARecords.applyAction(s.records,v.plan);assert.equal(n.companies[v.plan.buildCompanyId].status,'built');assert(n.companies[v.plan.buildCompanyId].slots.every(x=>x.owner==='Working'&&x.committed));s=setupCard(1);s.positions[2]='B';s.records.common.unemployed.Working={Gray:1,Green:0,Blue:0,White:1,Orange:0,Purple:0};v=J.evaluateAction(s,'AW');assert.equal(v.plan.ownerPayments.Capitalist,8);before=s.records.personal.Working.values.cash;const capBefore=s.records.personal.Capitalist.values.revenue;n=WCARecords.applyAction(s.records,v.plan);assert.equal(n.personal.Working.values.cash,before+8);assert.equal(n.personal.Capitalist.values.revenue,capBefore-8);});
test('cooperative-farm bonus never adds a zero-slot automated company to the allocation',()=>{const s=setupCard(2),automated='cc_dairy_farm_auto';s.records.common.unemployed.Working={Gray:3,Green:0,Blue:0,White:0,Orange:0,Purple:0};s.records.companies[automated].status='built';s.records.companies[automated].operating='yes';const v=J.evaluateAction(s,'AW');assert.equal(v.feasible,true);assert(v.plan.buildCompanyId);assert.equal(v.plan.allocations.some(a=>a.companyId===automated),false);assert(v.plan.allocations.every(a=>a.slots.length>0));const n=WCARecords.applyAction(s.records,v.plan);assert(n.companies[v.plan.buildCompanyId].slots.every(x=>x.owner==='Working'&&x.committed));});

test('AW rejects a partial company allocation even when a skilled-worker bonus was gained',()=>{const s=setupCard(7);s.positions[7]='B';s.records.common.unemployed.Working.Orange=1;const id='cc_college_init',plan={action:'AW',gainedSkill:'Orange',allocations:[{companyId:id,slots:[{index:0,skill:'Orange'}]}],ownerPayments:{}};assert.throws(()=>WCARecords.applyAction(s.records,plan),/全スロットを同時に埋める/);assert.equal(s.records.companies[id].slots.every(x=>x.owner==='empty'),true);});

test('all thirty cards can run every check and action evaluator without an unregistered effect',()=>{for(const number of Object.keys(J.CARD_DATA)){const s=setupCard(number);s.index=0;for(const check of s.card.order)assert.doesNotThrow(()=>J.evaluate(s,check,{}),`card ${number} check ${check}`);for(const action of ['AW','BGS','PB','STR','SA'])assert.doesNotThrow(()=>J.evaluateAction(s,action),`card ${number} action ${action}`);assert(J.evaluateAction(s,'SA').status!=='needsReview',`card ${number} SA`);}});
