const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const port=Number(process.argv[2]||9335),pageUrl=process.argv[3],sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{let targets;for(let i=0;i<30;i++){try{targets=await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();break;}catch{await sleep(200);}}const target=targets?.find(x=>x.type==='page');assert(target,'Edgeのページに接続できません');const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});let seq=0;const waiting=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&waiting.has(m.id)){waiting.get(m.id)(m);waiting.delete(m.id);}};const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;waiting.set(id,m=>m.error?reject(Error(m.error.message)):resolve(m.result));ws.send(JSON.stringify({id,method,params}));});const evaluate=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.value;
 await send('Page.enable');await send('Runtime.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await send('Page.navigate',{url:pageUrl});await sleep(1000);await evaluate(`localStorage.clear();location.reload()`);await sleep(1000);await evaluate(`document.querySelector('#setupWelcomeForm button[type=submit]').click()`);await sleep(300);
 await evaluate(`state.round=5;state.phase='scoring';state.records.personal.Working.unions.Food=true;state.records.personal.Working.values.vp=10;state.records.personal.Working.values.cash=38;state.records.personal.Working.values.loans=1;state.records.personal.Capitalist.values.vp=7;state.records.personal.Capitalist.values.capital=25;state.records.personal.Capitalist.values.revenue=100;state.records.personal.Capitalist.values.wealth=2;state.records.personal.Capitalist.values.loans=1;Object.assign(state.positions,{1:'A',2:'A',3:'A',4:'B',5:'C'});render()`);await sleep(150);
 assert.match(await evaluate(`document.querySelector('#flow').innerText`),/ラウンド5の得点計算[\s\S]*労働組合 1個 × 2VP[\s\S]*富マーカー 2 → 6/);await evaluate(`document.querySelector('#scoringApply').click()`);await sleep(150);assert.equal(await evaluate(`state.phase`),'gameEnd');assert.match(await evaluate(`document.querySelector('#flow').innerText`),/最終得点[\s\S]*貸付金：55のうち35支払い、-4VP[\s\S]*社会主義政策 3個：\+8VP[\s\S]*新自由主義政策 1個：\+1VP/);
 await evaluate(`document.querySelector('#gameEndApply').click()`);await sleep(150);assert.equal(await evaluate(`state.phase`),'finished');assert.match(await evaluate(`document.querySelector('#flow').innerText`),/GAME FINISHED[\s\S]*資本家階級の勝利/);assert.deepEqual(await evaluate(`({working:state.records.personal.Working.values.vp,capitalist:state.records.personal.Capitalist.values.vp,cash:state.records.personal.Working.values.cash,loans:state.records.personal.Working.values.loans})`),{working:16,capitalist:21,cash:3,loans:0});assert.equal(await evaluate(`document.documentElement.scrollWidth<=innerWidth`),true);const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.resolve(__dirname,'../scoring-mobile-qa.png'),Buffer.from(shot.data,'base64'));console.log('PASS round-five scoring and final result on mobile');await send('Browser.close');
})().catch(e=>{console.error(e);process.exitCode=1;});

