const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const port=Number(process.argv[2]||9333);
const pageUrl=process.argv[3];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

(async()=>{
 let targets;
 for(let i=0;i<30;i++){try{targets=await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();break;}catch{await sleep(200);}}
 const target=targets?.find(x=>x.type==='page');assert(target,'Edgeのページに接続できません');
 const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
 let seq=0;const waiting=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&waiting.has(m.id)){waiting.get(m.id)(m);waiting.delete(m.id);}};
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;waiting.set(id,m=>m.error?reject(Error(m.error.message)):resolve(m.result));ws.send(JSON.stringify({id,method,params}));});
 const evaluate=async expression=>(await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.value;
 await send('Page.enable');await send('Runtime.enable');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await send('Page.navigate',{url:pageUrl});await sleep(1200);
 await evaluate(`localStorage.clear();location.reload()`);await sleep(1200);
 assert.equal(await evaluate(`!!document.querySelector('#setupWelcome')`),true);
 await evaluate(`document.querySelector('#setupWelcomeForm button[type=submit]').click()`);await sleep(500);
 assert.deepEqual(await evaluate(`[...document.querySelectorAll('.main-tabs button:not([hidden])')].map(x=>x.textContent)`),['手番','政策','企業と労働者','国家','個人ボード']);
 assert.equal(await evaluate(`document.querySelector('#tab-trade').hidden`),true);
 await evaluate(`document.querySelector('#tab-policy').click()`);await sleep(200);
 assert.equal(await evaluate(`document.querySelectorAll('.policy-card').length`),7);
 assert.equal(await evaluate(`document.querySelector('.policy-card:nth-child(2) .policy-track .current').textContent`),'B');
 assert.equal(await evaluate(`document.querySelector('.policy-card:nth-child(6) p').textContent.includes('食料15（基本10＋関税5）・贅沢品9（基本6＋関税3）')`),true);
 assert.deepEqual(await evaluate(`[...document.querySelectorAll('[data-vote]')].map(x=>[x.value,x.nextElementSibling.textContent])`),[['17','袋の中 8'],['17','袋の中 8'],['17','袋の中 8']]);
 await evaluate(`document.querySelector('#tab-companies').click()`);await sleep(200);
 assert.equal(await evaluate(`document.querySelectorAll('.company-zone').length`),5);
 assert.equal(await evaluate(`document.querySelectorAll('.company-market .market-card').length`),0);
 assert.equal(await evaluate(`document.querySelectorAll('.class-capitalist .company-card').length`),4);
 assert.equal(await evaluate(`document.querySelectorAll('.class-working .company-card').length`),0);
 assert.equal(await evaluate(`document.querySelectorAll('.class-state .company-card').length`),3);
 assert.equal(await evaluate(`document.querySelector('.class-state .company-stats').textContent.includes('L2')`),true);
 assert.deepEqual(await evaluate(`[...document.querySelectorAll('.class-state .company-card')].map(x=>[x.querySelector('strong').textContent,x.querySelector('.company-output').textContent.trim(),x.querySelectorAll('.worker-token.empty').length])`),[['公立大学','4 教育',0],['地方テレビ局','3 影響力',2],['公立病院','4 医療',0]]);
 await evaluate(`document.querySelector('#tab-personal').click()`);await sleep(150);
 assert.deepEqual(await evaluate(`[...document.querySelectorAll('#classPick option')].map(x=>x.value)`),['Working','Capitalist']);
 await evaluate(`document.querySelector('#tab-state').click()`);await sleep(200);
 assert.equal(await evaluate(`document.querySelector('.treasury strong').textContent`),'120');
 assert.deepEqual(await evaluate(`[...document.querySelectorAll('.product-grid small')].slice(0,2).map(x=>x.textContent)`),['価格 5','価格 10']);
 assert.deepEqual(await evaluate(`[...document.querySelectorAll('.product-grid article>span')].map(x=>x.textContent)`),['医療','教育','影響力']);
 await evaluate(`document.querySelector('#tab-turn').click();document.querySelector('#next').click()`);await sleep(150);
 await evaluate(`document.querySelector('#p1').value='2';document.querySelector('#p2').value='7';document.querySelector('#next').click()`);await sleep(150);
 assert.equal(await evaluate(`document.querySelector('.judge-card').classList.contains('ready')`),true);
 await evaluate(`document.querySelector('#next').click()`);await sleep(150);
 assert.equal(await evaluate(`document.querySelector('.judge-result').textContent`),'法案の提議 (PB)を2段上げる、政策2を2段上げる');
 assert.deepEqual(await evaluate(`[...document.querySelectorAll('#moves .movement')].map(x=>[x.querySelector('select').value,x.querySelector('input').value])`),[['PB','2'],['政策2','2']]);
 await evaluate(`document.querySelector('#next').click()`);await sleep(150);
 assert.equal(await evaluate(`document.querySelectorAll('[data-judge-answer]').length`),0);
 assert.equal(await evaluate(`[...document.querySelectorAll('.judge-reason li')].some(x=>x.textContent.includes('贅沢品')&&x.textContent.includes('海外市場（基本6＋関税3）'))`),true);
 assert.equal(await evaluate(`[...document.querySelectorAll('.judge-reason li')].filter(x=>x.textContent.includes('健康')||x.textContent.includes('教育')).some(x=>x.textContent.includes('海外市場'))`),false);
 await evaluate(`state.phase='action';state.actions={0:['SA','STR','DEM','AW','BGS'],1:['PB']};render()`);await sleep(150);
 assert.match(await evaluate(`document.querySelector('.action-advice strong').textContent`),/法案の提議 \(PB\)：実行可能/);
 assert.match(await evaluate(`document.querySelector('.action-advice p').textContent`),/政策/);
 assert.equal(await evaluate(`document.querySelector('#first').value`),'yes');
 await evaluate(`window.qaBeforeProposal=E.copy(state);document.querySelector('#executed').click();document.querySelector('#next').click()`);await sleep(150);
 assert.equal(await evaluate(`Object.keys(state.proposals).length`),1);
 assert.equal(await evaluate(`state.records.personal.Working.values.billMarkers`),2);
 await evaluate(`document.querySelector('#tab-policy').click()`);await sleep(150);
 assert.equal(await evaluate(`document.querySelectorAll('.policy-card.has-bill').length`),1);
 assert.match(await evaluate(`document.querySelector('.bill-status').textContent`),/労働者オートマ.*投票待ち/);
 assert.equal(await evaluate(`document.querySelectorAll('.proposal-item').length`),0);
 assert.equal(await evaluate(`document.querySelector('#events').innerText.includes('法案と投票')||document.querySelector('#events').innerText.includes('次ラウンドの準備')`),false);
 const proposalShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.resolve(__dirname,'../proposal-mobile-qa.png'),Buffer.from(proposalShot.data,'base64'));
 assert.equal(await evaluate(`document.querySelectorAll('[data-proposal-result]').length`),0);
 assert.match(await evaluate(`document.querySelector('#events summary').textContent`),/手動補正/);
 await evaluate(`state=window.qaBeforeProposal;activeTab='turn';render()`);await sleep(150);
 await evaluate(`state.actions={0:['STR','DEM','AW','BGS','PB'],1:['SA']};render()`);await sleep(150);
 assert.match(await evaluate(`document.querySelector('.action-advice strong').textContent`),/特殊アクション \(SA\)：現物確認/);
 assert.match(await evaluate(`document.querySelector('.action-advice p').textContent`),/実物AIカード下部/);
 assert.equal(await evaluate(`document.querySelector('#first').value`),'unknown');
 await evaluate(`state.actions={0:['SA','STR','DEM','AW','PB'],2:['BGS']};render()`);await sleep(150);
 assert.equal(await evaluate(`document.querySelector('#first').value`),'yes');
 await evaluate(`document.querySelector('#executed').click();document.querySelector('#next').click()`);await sleep(150);
 assert.equal(await evaluate(`state.phase`),'end');
 assert.equal(await evaluate(`state.records.personal.Working.values.health`),3);
 assert.equal(await evaluate(`state.records.personal.Working.values.cash`),15);
 assert.match(await evaluate(`document.querySelector('#flow').textContent`),/健康を人口3個使用/);
 await evaluate(`document.querySelector('#useResource').click()`);await sleep(150);
 assert.deepEqual(await evaluate(`{const w=state.records.personal.Working.values;({health:w.health,prosperity:w.prosperity,vp:w.vp,workerCount:w.workerCount,population:w.population,gray:state.records.common.unemployed.Working.Gray})}`),{health:0,prosperity:1,vp:3,workerCount:11,population:3,gray:2});
 await evaluate(`state.records.companies.cc_supermarket_pool.status='market';document.querySelector('#next').click()`);await sleep(150);
 assert.equal(await evaluate(`state.phase`),'player');
 assert.match(await evaluate(`document.querySelector('#flow h2').textContent`),/資本家プレイヤー/);
 await evaluate(`document.querySelector('#capQty').value='2';document.querySelector('#capPurchase').click()`);await sleep(150);
 assert.deepEqual(await evaluate(`{const c=state.records.personal.Capitalist.values;({food:c.food,revenue:c.revenue,stateCash:state.records.personal.State.values.cash})}`),{food:3,revenue:90,stateCash:145});
 await evaluate(`document.querySelector('#capBuild').click()`);await sleep(100);
 assert.equal(await evaluate(`document.querySelector('#establishPick').value`),'cc_supermarket_pool');
 await evaluate(`document.querySelector('#establishForm button[type=submit]').click()`);await sleep(200);
 assert.equal(await evaluate(`state.records.companies.cc_supermarket_pool.status`),'built');
 assert.equal(await evaluate(`state.records.personal.Capitalist.values.revenue`),74);
 await evaluate(`document.querySelector('#capSellCompany').value='cc_supermarket_pool';document.querySelector('#capSell').click()`);await sleep(150);
 assert.equal(await evaluate(`state.records.companies.cc_supermarket_pool.status`),'discarded');
 assert.equal(await evaluate(`state.records.personal.Capitalist.values.revenue`),90);
 await evaluate(`document.querySelector('#capLobby').click()`);await sleep(150);
 assert.equal(await evaluate(`state.records.personal.Capitalist.values.influence`),4);
 await evaluate(`document.querySelector('#capPressure').click()`);await sleep(150);
 assert.equal(await evaluate(`state.records.common.values.capitalistVotesOutside`),14);
 await evaluate(`document.querySelector('#capPropose').click()`);await sleep(150);
 assert.equal(await evaluate(`state.proposals['1'].proposer`),'Capitalist');
 assert.equal(await evaluate(`state.proposals['1'].target`),'A');
 assert.equal(await evaluate(`state.records.personal.Capitalist.values.billMarkers`),2);
 await evaluate(`document.querySelector('#playerEnd').click()`);await sleep(150);
 assert.equal(await evaluate(`state.phase`),'start');
 assert.equal(await evaluate(`state.turn`),2);
 await evaluate(`state.actions={0:['AW','BGS','STR','DEM'],1:['SA'],2:['PB']};state.policies={0:['4','6'],1:['5'],2:['2']};state.aside={actions:{},policies:{1:'test',3:'test',7:'test'}};render()`);await sleep(150);
 assert.equal(await evaluate(`{const chips=[...document.querySelectorAll('.priority-row:last-child .action .chip')];Math.max(...chips.map(x=>x.getBoundingClientRect().top))-Math.min(...chips.map(x=>x.getBoundingClientRect().top))}`),0);
 assert.equal(await evaluate(`document.querySelector('.priority-row:last-child').getBoundingClientRect().height<60`),true);
 assert.equal(await evaluate(`document.documentElement.scrollWidth<=innerWidth`),true);
 await evaluate(`document.querySelector('.board').scrollIntoView()`);await sleep(100);
 const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.resolve(__dirname,'../common-board-mobile-qa.png'),Buffer.from(shot.data,'base64'));
 await send('Browser.close');console.log('PASS boards, automatic policy check, and mobile width');
})().catch(e=>{console.error(e);process.exitCode=1;});
