require('../dist/companies.js');require('../dist/boards.js');require('../dist/judge.js');require('../dist/capitalist.js');
const E=require('../dist/engine.js'),{test}=require('node:test'),assert=require('node:assert/strict');
const trade={exportCard:{name:'両オートマ用',offers:[{resource:'food',quantity:3,revenue:20}]},businessDeals:[{name:'商取引',food:2,luxury:1,cost:18,tariffA:16,tariffB:8}]};
function setup(){return E.reduce(E.initial(),{type:'setup',players:2,immigrant:'',market:[],automaClass:'Both',workingDeck:['1','2','3','4','5'],capitalistDeck:['5','7','9','20','21'],trade,confirmed:true});}
function checks(s,movement){s=E.reduce(s,{type:'start'});for(let i=0;i<4;i++)s=E.reduce(s,{type:'check',confirmed:true,note:'両オートマ進行テスト',movements:i===0&&movement?[movement]:[]});return s;}
function workingTurn(s,movement){s=checks(s,movement);s=E.reduce(s,{type:'action',first:'no',second:'no',plan:{action:'PRESSURE'},note:'政治的圧力'});return E.reduce(s,{type:'end'});}
function capitalistTurn(s,movement){s=checks(s,movement);return E.reduce(s,{type:'action',first:'no',second:'no',note:'政治的圧力'});}
test('dual-automa setup owns independent priorities, decks, and both automa participants',()=>{const s=setup(),w=s.automaStates.Working,c=s.automaStates.Capitalist;assert.equal(s.automaMode,'Both');assert.equal(s.automaClass,'Working');assert.deepEqual(s.records.participants,{Working:'automa',Capitalist:'automa',Middle:'absent',State:'absent'});assert.deepEqual(E.rank({...s,...w,automaClass:'Working'},'actions'),['AW','BGS','PB','SA','STR','DEM']);assert.deepEqual(E.rank({...s,...c,automaClass:'Capitalist'},'actions'),['BC','SFM','PB','SA','LOB','SC']);assert.deepEqual(w.aiDeck,['1','2','3','4','5']);assert.deepEqual(c.aiDeck,['5','7','9','20','21']);});
test('a passed policy updates both automata policy priorities by their own desired positions',()=>{let s=setup();s.phase='election';s.election={mode:'immediate',step:'declare',queue:[{id:'1',proposer:'Working',from:'C',target:'A',immediate:true}],current:0,returnPhase:'scoring',results:[]};s=E.reduce(s,{type:'electionDeclare',sides:{Working:'favor',Capitalist:'against'},cubes:{Working:5,Capitalist:0,Middle:0}});s=E.reduce(s,{type:'electionResolve',spends:{},autoCoinSuccesses:{Working:0,Capitalist:0}});const w={...s,...s.automaStates.Working,automaClass:'Working'},c={...s,...s.automaStates.Capitalist,automaClass:'Capitalist'};assert.equal(s.positions['1'],'A');assert.equal(w.aside.policies['1'],'desired');assert.equal(E.locate(c,'policies','1'),1);});
test('a Capitalist immediate vote returns to the next Working automa turn',()=>{let s=workingTurn(setup());s.phase='action';s.card={number:'7',...CCAJudge.CARD_DATA['7']};s.actions={0:CCAJudge.ACTIONS.filter(x=>x!=='PB'),2:['PB']};const verdict=CCAJudge.evaluateAction(s,'PB');verdict.plan.proposals[0].immediate=true;verdict.plan.proposals[0].immediateCost=1;s=E.reduce(s,{type:'action',first:'yes',plan:verdict.plan,policyReviewed:true});assert.equal(s.election.returnPhase,'automaNext');const proposal=E.currentElection(s),sides={Working:E.automaStance(s,proposal,'Working'),Capitalist:'favor'};s=E.reduce(s,{type:'electionDeclare',sides,cubes:{Working:5,Capitalist:0,Middle:0}});s=E.reduce(s,{type:'electionResolve',spends:{},autoCoinSuccesses:{Working:0,Capitalist:0}});assert.deepEqual({automa:s.automaClass,turn:s.turn,phase:s.phase},{automa:'Working',turn:2,phase:'start'});});
test('dual-automa handoff preserves each priority board and completes a full round',()=>{let s=setup();s=workingTurn(s,{series:'actions',card:'AW',up:2});assert.equal(s.automaClass,'Capitalist');assert.equal(s.phase,'start');assert.notEqual(E.locate({...s,...s.automaStates.Working,automaClass:'Working'},'actions','AW'),E.locate({...s,...s.automaStates.Capitalist,automaClass:'Capitalist'},'actions','BC'));s=capitalistTurn(s,{series:'actions',card:'BC',up:1});assert.equal(s.automaClass,'Working');assert.equal(s.turn,2);assert.equal(s.phase,'start');const wAfter=JSON.stringify(s.automaStates.Working.actions),cAfter=JSON.stringify(s.automaStates.Capitalist.actions);for(let turn=2;turn<=5;turn++){s=workingTurn(s);assert.equal(s.automaClass,'Capitalist');s=capitalistTurn(s);}assert.equal(s.phase,'production');assert.equal(s.production.step,'produce');assert.equal(s.turn,5);s=E.reduce(s,{type:'productionProduce'});const food=WCARecords.foodNeedPreview(s.records,s.positions[6]),capitalist=Math.min(food.shortage,food.capitalistStock);s=E.reduce(s,{type:'productionNeeds',plan:{capitalist,foreign:food.shortage-capitalist}});s=E.reduce(s,{type:'productionImf',manual:false});s=E.reduce(s,{type:'productionTaxes'});assert.equal(s.phase,'scoring');s=E.reduce(s,{type:'scoringApply'});assert.equal(s.phase,'preparation');const market=WCA_COMPANIES.filter(d=>d.class==='Capitalist'&&!d.tags.includes('Initial_Setup')&&s.records.companies[d.id]?.status==='unbuilt').slice(0,4).map(d=>d.id);s=E.reduce(s,{type:'preparationTrade',value:trade});s=E.reduce(s,{type:'preparationApply',confirmed:true,plan:{market,immigration:['Gray']}});assert.deepEqual({round:s.round,turn:s.turn,phase:s.phase,automa:s.automaClass},{round:2,turn:1,phase:'start',automa:'Working'});assert.equal(JSON.stringify(s.automaStates.Working.actions),wAfter);assert.equal(JSON.stringify(s.automaStates.Capitalist.actions),cAfter);assert.deepEqual(E.validate(JSON.parse(JSON.stringify(s))),s);});
