const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../dist/engine.js');
function checking(){let s=E.reduce(E.initial(),{type:'start'});return E.reduce(s,{type:'card',number:'14',order:['AW','PB','BGS','STR'],policies:['2','7'],bonus:'共同農場'});}
function ready(){let s=checking();for(let i=0;i<4;i++)s=E.reduce(s,{type:'check',confirmed:true,note:'全条件不成立',movements:[]});return s;}
test('P01 initial priorities and aside',()=>{const s=E.initial();assert.equal(E.rank(s,'actions')[0],'AW');assert.equal(E.rank(s,'policies')[0],'1');assert.deepEqual(Object.keys(s.aside.policies),['3','7']);});
test('P02 P03 same row inserts away from marker',()=>{const s=E.initial();E.move(s,'actions','SA',1);E.move(s,'policies','2',1);assert.deepEqual(s.actions[1],['AW','BGS','PB','SA']);assert.deepEqual(s.policies[1],['1','5','2']);});
test('P04 preserve interleaved movement order',()=>{const s=E.initial();for(const [id,n] of [['AW',1],['BGS',1],['AW',1],['AW',1],['BGS',2]])E.move(s,'actions',id,n);assert.deepEqual(s.actions[4],['AW','BGS']);});
test('P05 independent compression retains row order',()=>{const s={actions:{0:['SA'],2:['AW','PB'],5:['BGS']},policies:{0:['2'],3:['1']}};E.compress(s,'actions');E.compress(s,'policies');assert.deepEqual(s.actions,{0:['SA'],1:['AW','PB'],2:['BGS']});assert.deepEqual(s.policies,{0:['2'],1:['1']});});
test('P06 only second executed action descends and gap collapses',()=>{const s=ready();s.actions={0:['SA','STR','DEM'],1:['PB'],2:['BGS'],3:['AW']};const n=E.reduce(s,{type:'action',first:'no',second:'yes'});assert.equal(E.rank(n,'actions')[0],'AW');assert.deepEqual(n.actions[0],['SA','STR','DEM','BGS']);assert.deepEqual(n.actions[2],['AW']);});
test('P07 political pressure does not lower a priority card',()=>{const s=ready(),n=E.reduce(s,{type:'action',first:'no',second:'no'});assert.deepEqual(s.actions,n.actions);assert.match(n.log.at(-1).note,/PRESSURE/);});
test('an unavailable Special Action falls through to second priority, then Political Pressure',()=>{const first=ready();first.actions={0:['PB','STR','DEM','AW','BGS'],1:['SA']};const second=E.reduce(first,{type:'action',first:'no',second:'yes',policyReviewed:true});assert.equal(E.locate(second,'actions','SA'),1);assert.equal(E.locate(second,'actions','PB'),0);const last=ready();last.actions={0:['SA','STR','AW','BGS','PB'],1:['DEM']};const pressure=E.reduce(last,{type:'action',first:'no',second:'no'});assert.deepEqual(pressure.actions,last.actions);assert.match(pressure.log.at(-1).note,/PRESSURE/);});
test('P08 unknown cannot fall back',()=>assert.throws(()=>E.reduce(ready(),{type:'action',first:'unknown',second:'yes'}),/確認/));
test('P09 aside ignores movement',()=>{const s=checking();const n=E.reduce(s,{type:'check',confirmed:true,note:'政策3 +2',movements:[{series:'policies',card:'3',up:2}]});assert.equal(n.aside.policies['3'],'initial');assert.equal(n.log.at(-1).event.movements[0].applied,false);});
test('P10 final round policy7 never returns',()=>{let s=E.initial();s.round=4;s.positions['7']='A';s=E.reduce(s,{type:'round',confirmed:true});assert.equal(s.aside.policies['7'],'finalRound');s=E.reduce(s,{type:'policy',id:'7',position:'C',result:'passed'});assert.equal(s.aside.policies['7'],'finalRound');});
test('P11 immutable reduction permits snapshot undo and single reapply',()=>{const s=ready(),snapshot=E.copy(s),event={type:'action',first:'yes'};const n=E.reduce(s,event);assert.deepEqual(s,snapshot);assert.deepEqual(E.reduce(snapshot,event).actions,n.actions);});
test('P12 serializable complete state and validation',()=>{const s=checking();assert.deepEqual(E.validate(JSON.parse(JSON.stringify(s))),s);const broken=E.copy(s);broken.actions[1].push('AW');assert.throws(()=>E.validate(broken),/重複/);});
test('P13 unsupported bonus requires explicit manual check',()=>{const s=checking();assert.throws(()=>E.reduce(s,{type:'check',note:'共同農場未判定',confirmed:false,movements:[]}),/確認/);});
test('P14 P15 bonuses remain annotations with no resource or policy side effects',()=>{for(const [number,order,bonus] of [['13',['BGS','AW','PB','STR'],'資金ボーナス'],['29',['PB','AW','BGS','STR'],'法案2つ']]){const s=E.reduce(E.reduce(E.initial(),{type:'start'}),{type:'card',number,order,policies:['6','2'],bonus});assert.deepEqual(s.policies,E.initial().policies);assert.equal(s.card.bonus,bonus);}});
test('four checks compress once, not during checks',()=>{let s=checking();s=E.reduce(s,{type:'check',confirmed:true,note:'AW+8',movements:[{series:'actions',card:'AW',up:8}]});assert.equal(E.locate(s,'actions','AW'),9);for(let i=0;i<3;i++)s=E.reduce(s,{type:'check',confirmed:true,note:'なし',movements:[]});assert.equal(E.locate(s,'actions','AW'),2);assert.equal(s.phase,'action');});
test('action priority moving below the bottom stops on the bottom row',()=>{const s=ready(),selected=E.rank(s,'actions')[0],n=E.reduce(s,{type:'action',first:'yes'});assert.equal(E.locate(n,'actions',selected),0);});
test('policy events and numbered restoration',()=>{let s=E.initial();s=E.reduce(s,{type:'policy',id:'1',position:'A',result:'pending'});assert.equal(s.aside.policies['1'],'bill:other');assert.equal(s.positions['1'],'B');s=E.reduce(s,{type:'policy',id:'1',position:'A',result:'failed'});s=E.reduce(s,{type:'round',confirmed:true});assert.equal(s.policies[0].at(-1),'1');s=E.reduce(s,{type:'policy',id:'1',position:'A',result:'passed'});assert.equal(s.aside.policies['1'],'desired');});
test('DEM and STR have distinct restoration triggers',()=>{let s=ready();s.actions={0:['SA','STR','AW','BGS','PB'],2:['DEM']};s=E.reduce(s,{type:'action',first:'yes'});assert.equal(s.aside.actions.DEM,'demonstration');s=E.reduce(s,{type:'strikeAside'});s=E.reduce(s,{type:'end'});s=E.reduce(s,{type:'playerEnd'});s=E.reduce(s,{type:'round',confirmed:true});assert.equal(s.aside.actions.DEM,'demonstration');assert.equal(E.locate(s,'actions','STR'),0);s=E.reduce(s,{type:'demReturn'});assert.equal(s.actions[0].at(-1),'DEM');});
test('second-priority DEM removal immediately collapses the empty row',()=>{const s=ready();s.actions={0:['SA','STR','BGS','PB'],1:['DEM'],2:['AW']};const n=E.reduce(s,{type:'action',first:'no',second:'yes'});assert.equal(n.aside.actions.DEM,'demonstration');assert.equal(E.locate(n,'actions','AW'),1);assert.deepEqual(E.rows(n,'actions'),[1,0]);});
test('failed immediate vote keeps policy priority; passed vote places or sets it aside',()=>{let s=E.initial(),before=E.copy(s.policies);s=E.reduce(s,{type:'policy',id:'1',position:'C',result:'failed'});assert.deepEqual(s.policies,before);s=E.reduce(s,{type:'policy',id:'1',position:'B',result:'passed'});assert.equal(E.locate(s,'policies','1'),0);assert.equal(s.policies[0].at(-1),'1');s=E.reduce(s,{type:'policy',id:'1',position:'A',result:'passed'});assert.equal(s.aside.policies['1'],'desired');});
test('set-aside policies return in number order at the far end of their rows',()=>{let s=E.initial();s=E.reduce(s,{type:'policy',id:'5',position:'A',result:'pending'});s=E.reduce(s,{type:'policy',id:'1',position:'A',result:'pending'});s=E.reduce(s,{type:'policy',id:'5',position:'A',result:'failed'});s=E.reduce(s,{type:'policy',id:'1',position:'A',result:'failed'});s=E.reduce(s,{type:'round',confirmed:true});assert.deepEqual(s.policies[0],['2','4','6','1','5']);});
test('duplicate card checks and policies rejected',()=>{const s=E.reduce(E.initial(),{type:'start'});assert.throws(()=>E.reduce(s,{type:'card',order:['AW','AW','BGS','STR'],policies:['2','7']}));});

