const {chromium}=require(process.argv[2]),{pathToFileURL}=require('node:url'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(pathToFileURL(path.resolve(__dirname,'../dist/index.html')).href);
 await page.evaluate(()=>{const first=['W-Blue-1','W-Green-1','M-White-1'],immigrationDeck=[...first,...Object.keys(WCA.IMMIGRATION_CARD_DATA).filter(id=>!first.includes(id))],trade={exportCard:{name:'輸出A',offers:[{resource:'food',quantity:3,revenue:20},{resource:'food',quantity:8,revenue:50}]},businessDeals:[{name:'取引1',food:2,luxury:1,cost:20}]};state=E.reduce(E.initial(),{type:'setup',players:2,market:[],immigrationDeck,confirmed:true});state.phase='preparation';state.positions[7]='C';state.preparationTrade=trade;WCARecords.resetUi();render();});
 assert.equal(await page.locator('[data-prep-immigration]').count(),0);assert.match(await page.locator('#flow').innerText(),/アプリが移民カードを2枚引いて処理/);
 await page.locator('#prepActionCards').check();await page.locator('#prepConfirmed').check();await page.locator('#preparationApply').click();
 const instructions=await page.locator('#boardInstructionDialog').innerText();assert.match(instructions,/移民カード1：労働者階級・食料／中産階級・未熟練/);assert.match(instructions,/移民カード2：労働者階級・未熟練／中産階級・医療/);assert.match(instructions,/山札の底へ戻す/);
 assert.deepEqual(await page.evaluate(()=>({cards:state.lastPreparation.immigrationCards.map(x=>x.id),bottom:state.immigrationDeck.slice(-3)})),{cards:['W-Green-1','M-White-1'],bottom:['W-Blue-1','W-Green-1','M-White-1']});assert.deepEqual(errors,[]);console.log('PASS immigration UI: no manual inputs, automatic draw, board instructions, bottom rotation');
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
