require('../dist/companies.js');require('../dist/boards.js');
const J=require('../dist/judge.js'),E=require('../dist/engine.js'),{test}=require('node:test'),assert=require('node:assert/strict');
function card(number,order,policies){let s=E.reduce(E.initial(),{type:'setup',players:2,immigrant:'Gray',market:[],confirmed:true});s=E.reduce(s,{type:'start'});return E.reduce(s,{type:'card',number,order,policies,bonus:''});}
test('policy check moves PB and the matching policy in card order',()=>{const s=card('14',['AW','PB','BGS','STR'],['2','7']);s.index=1;const v=J.evaluate(s,'PB');assert.equal(v.status,'ready');assert.deepEqual(v.movements,[{series:'actions',card:'PB',up:2},{series:'policies',card:'2',up:2}]);});
test('policy check falls back to SA when both policy cards are aside',()=>{const s=card('14',['AW','PB','BGS','STR'],['2','7']);s.index=1;s.aside.policies['2']='bill';for(const row of Object.keys(s.policies))s.policies[row]=s.policies[row].filter(x=>x!=='2');const v=J.evaluate(s,'PB');assert.deepEqual(v.movements,[{series:'actions',card:'SA',up:1}]);});
test('strike check always raises labor policy in section C',()=>{const s=card('30',['PB','BGS','AW','STR'],['6','7']);s.index=3;s.positions[2]='C';const v=J.evaluate(s,'STR');assert.equal(v.movements.some(x=>x.series==='policies'&&x.card==='2'&&x.up===1),true);});
test('foreign market has no stock input and only adds policy tariff to food and luxury',()=>{assert.deepEqual(['A','B','C'].map(x=>J.foreignMarketPrice('food',x)),[20,15,10]);assert.deepEqual(['A','B','C'].map(x=>J.foreignMarketPrice('luxury',x)),[12,9,6]);const s=card('13',['BGS','AW','PB','STR'],['7','2']),v=J.evaluate(s,'BGS');assert.equal(v.status,'ready');assert.deepEqual(v.questions,[]);assert.equal(v.movements.filter(x=>x.card==='BGS').length,3);assert.match(v.reasons.find(x=>x.includes('贅沢品')),/海外市場（基本6＋関税3）/);assert.doesNotMatch(v.reasons.find(x=>x.includes('健康')),/海外市場/);assert.doesNotMatch(v.reasons.find(x=>x.includes('教育')),/海外市場/);});
test('workers check proves the initial union maximum without asking',()=>{const s=card('', ['AW','PB','BGS','STR'],['2','7']),v=J.evaluate(s,'AW');assert.equal(v.status,'ready');assert.deepEqual(v.questions,[]);assert.match(v.reasons.join(' '),/設立できる労働組合なし/);assert.match(v.reasons.join(' '),/最大雇用/);});
test('skilled-worker bonus changes every workers-check condition before evaluation',()=>{const s=card('7',J.CARD_DATA['7'].order,J.CARD_DATA['7'].policies);s.positions[7]='B';for(const c of Object.values(s.records.companies))if(c.status==='built')for(const slot of c.slots)slot.owner='Working';s.records.common.unemployed.Working={Gray:0,Green:0,Blue:0,White:0,Orange:0,Purple:0};const v=J.evaluate(s,'AW'),demo=v.movements.find(x=>x.card==='DEM');assert.deepEqual(demo,{series:'actions',card:'DEM',up:1});assert.match(v.reasons.join(' '),/ボーナス反映後：失業者1、空きスロット0/);});
test('cooperative-farm bonus removes its assigned workers before all workers-check conditions',()=>{const s=card('2',J.CARD_DATA['2'].order,J.CARD_DATA['2'].policies);for(const c of Object.values(s.records.companies))if(c.status==='built')for(const slot of c.slots)slot.owner='Working';s.records.common.unemployed.Working={Gray:3,Green:0,Blue:0,White:0,Orange:0,Purple:0};const v=J.evaluate(s,'AW');assert.equal(v.movements.some(x=>x.card==='DEM'),false);assert.match(v.reasons.join(' '),/ボーナス反映後：失業者0、空きスロット0/);});
test('known sample card mismatch is never silently accepted',()=>{const s=card('14',['PB','AW','BGS','STR'],['2','7']),v=J.evaluate(s,'PB');assert.equal(v.status,'needsReview');assert.match(v.warnings.join(' '),/一致しません/);});
test('action phase automatically selects the highest policy and adjacent target',()=>{const s=card('', ['AW','PB','BGS','STR'],['2','7']),v=J.evaluateAction(s,'PB');assert.equal(v.feasible,true);assert.match(v.summary,/政策1：C → B/);});
test('goods action selects a legal purchase from recorded stock and prices',()=>{const s=card('', ['AW','PB','BGS','STR'],['2','7']),v=J.evaluateAction(s,'BGS');assert.equal(v.feasible,true);assert.match(v.summary,/健康3個/);assert.match(v.summary,/国家 3/);});
test('all registered special actions are automatic while an unregistered card stays with the physical card',()=>{for(const number of Object.keys(J.CARD_DATA)){const c=J.CARD_DATA[number],s=card(number,c.order,c.policies.map(String)),v=J.evaluateAction(s,'SA');assert.notEqual(v.feasible,null);if(v.feasible)assert(v.plan);}const s=card('', ['AW','PB','BGS','STR'],['2','7']),v=J.evaluateAction(s,'SA');assert.equal(v.feasible,null);assert.match(v.summary,/実物AIカード下部/);});
test('initial demonstration is rejected from unemployed and empty-slot counts',()=>{const s=card('', ['AW','PB','BGS','STR'],['2','7']),v=J.evaluateAction(s,'DEM');assert.equal(v.feasible,false);assert.match(v.reasons.join(' '),/失業者.*空きスロット/);});
test('two-player immediate vote uses influence after spending and cubes in the bag',()=>{const s=card('30',['PB','BGS','AW','STR'],['6','7']);let v=J.immediateVote2P(s);assert.equal(v.possible,false);s.records.personal.Working.values.influence=3;v=J.immediateVote2P(s);assert.equal(v.possible,true);assert.match(v.reason,/カード#30の2個を反映/);s.records.common.values.workingVotesOutside=21;v=J.immediateVote2P(s);assert.equal(v.possible,false);});
test('final-round policy 6 is ignored unless an immediate vote can be called',()=>{const s=card('30',['PB','BGS','AW','STR'],['6','7']);s.round=5;let v=J.evaluate(s,'PB');assert.deepEqual(v.movements,[{series:'actions',card:'SA',up:1}]);s.records.personal.Working.values.influence=3;v=J.evaluate(s,'PB');assert.equal(v.movements.some(x=>x.series==='policies'&&x.card==='6'),true);});

test('vote-cube special actions require results from the physical bag',()=>{for(const number of ['1','3']){const c=J.CARD_DATA[number],s=card(number,c.order,c.policies),v=J.evaluateAction(s,'SA');assert.equal(v.feasible,true);assert.equal(v.plan.requiresCubeInput,true);assert.match(v.summary,/実物の袋/);}});
