require('../dist/companies.js');require('../dist/boards.js');require('../dist/middle.js');require('../dist/judge.js');require('../dist/capitalist.js');require('../dist/action-card-data.js');require('../dist/player-cards.js');
const E=require('../dist/engine.js'),R=globalThis.WCARecords,M=globalThis.MiddleClass,P=globalThis.PlayerCards,{test}=require('node:test'),assert=require('node:assert/strict');
const market=['mc_game_shop','mc_training_center','mc_organic_farm'];
function setup(cards=false){return E.reduce(E.initial(),{type:'setup',players:3,automaClass:'Middle',middleSkill:'Green',middleMarket:market,immigrationDeck:Object.keys(E.IMMIGRATION_CARD_DATA),market:R.randomMarket(null),managePlayerCards:cards,confirmed:true});}
function player(s){s=E.copy(s);s.phase='player';return s;}
const basic=(s,plan)=>E.reduce(s,{type:'middleBasic',plan,cardUid:s.playerCards?.classes.Middle.hand[0]});
function checks(s){s=E.reduce(s,{type:'start'});while(s.phase==='checks')s=E.reduce(s,{type:'check',confirmed:true,movements:[],note:'進行確認'});return s;}
function working(s){s=checks(s);s=E.reduce(s,{type:'action',first:'no',second:'no',plan:{action:'PRESSURE'}});while(R.nextFreeResource(s.records))s=E.reduce(s,{type:'freeAction',resource:R.nextFreeResource(s.records)});return E.reduce(s,{type:'end'});}
test('three-player setup automatically supplies the first Capitalist market',()=>{const s=E.reduce(E.initial(),{type:'setup',players:3,middleSkill:'Blue',immigrationDeck:E.randomImmigrationDeck(),confirmed:true});assert.equal(s.records.setup.market.length,4);assert.equal(s.records.setup.pending.length,0);});
test('invalid three-player setup and corrupt Middle saves are rejected',()=>{assert.throws(()=>E.reduce(E.initial(),{type:'setup',players:3,confirmed:true,middleSkill:'Gray',immigrationDeck:E.randomImmigrationDeck()}),/熟練/);for(const change of [s=>s.records.personal.Middle.values.cash=null,s=>s.records.personal.Middle.values.prosperityStep=11,s=>s.records.personal.Middle.values.food=9,s=>s.records.participants.Middle='absent',s=>s.automaMode='Single']){const s=setup();change(s);assert.throws(()=>E.validate(s),/不正|容量/);}});
test('export earns one VP per transaction, excludes purchased goods and rejects duplicate offers',()=>{const r=setup().records;r.trade.exportCard.offers=[{resource:'food',quantity:2,revenue:15},{resource:'health',quantity:3,revenue:20}];Object.assign(r.personal.Middle.values,{food:2,health:3,consumedHealth:9});const n=M.basic(r,{},{action:'SFM',transactions:[0,1]});assert.equal(n.personal.Middle.values.cash,75);assert.equal(n.personal.Middle.values.vp,2);assert.equal(n.personal.Middle.values.consumedHealth,9);assert.throws(()=>M.basic(r,{},{action:'SFM',transactions:[0,0]}),/取引/);r.personal.Middle.values.health=0;assert.throws(()=>M.basic(r,{},{action:'SFM',transactions:[1]}),/在庫/);});
test('education and swaps keep commitments, wage raises commit employees, and loan repayment is a free action',()=>{let s=player(setup(true)),r=s.records,c=r.companies.state_technical_university_init3;c.slots[1].committed=true;r.personal.Middle.values.consumedEducation=3;s.records=M.free(s.records,s.positions,{action:'USE',resource:'education',worker:'c:state_technical_university_init3:1',skill:'Purple'});assert.equal(s.records.companies.state_technical_university_init3.slots[1].committed,true);assert.equal(s.playerCards.used,false);assert.equal(s.playerCards.classes.Middle.hand.length,7);s.records=M.free(s.records,s.positions,{action:'SWAP',id:'state_technical_university_init3',index:1,skill:'Green'});assert.equal(s.records.companies.state_technical_university_init3.slots[1].skill,'Green');assert.equal(s.records.companies.state_technical_university_init3.slots[1].committed,true);s.records.companies.mc_convenience_store_init.slots[1]={owner:'Working',skill:'Gray',committed:false};s.records=M.free(s.records,s.positions,{action:'WAGE',id:'mc_convenience_store_init',wage:'L3'});assert.equal(s.records.companies.mc_convenience_store_init.slots[1].committed,true);assert.throws(()=>E.reduce(s,{type:'middleFree',plan:{action:'WAGE',id:'mc_convenience_store_init',wage:'L2'}}),/誓約/);s.records.personal.Middle.values.cash=60;s.records.personal.Middle.values.loans=1;s.records=M.free(s.records,s.positions,{action:'LOAN'});assert.equal(s.records.personal.Middle.values.cash,10);assert.equal(s.records.personal.Middle.values.loans,0);});
test('Working strike targets employees even when Middle owners are committed; only employees strike',()=>{let s=setup();s.positions[2]='C';for(const d of WCA_COMPANIES)for(const x of s.records.companies[d.id].slots)if(x.owner==='Working')x.committed=true;for(const id of ['mc_convenience_store_init','mc_doctors_office_init']){const c=s.records.companies[id];c.slots[0].committed=true;c.slots[1]={owner:'Working',skill:'Gray',committed:false};c.wage='L1';}s.card={number:'1',...WCAJudge.CARD_DATA['1']};const result=WCAJudge.evaluateAction(s,'STR');assert.equal(result.feasible,true);const n=R.applyAction(s.records,result.plan);for(const id of result.plan.companyIds){assert.equal(n.companies[id].slots[1].committed,true);assert.equal(n.companies[id].strike,true);}const p=R.productionPreview(n);assert.equal(p.items.find(x=>x.id==='mc_convenience_store_init').amount,2);assert.equal(p.items.find(x=>x.id==='mc_convenience_store_init').wage,0);});
test('preparation discards only unretained Middle market cards and draws separate immigrants',()=>{const r=setup().records,positions={1:'C',2:'B',3:'A',4:'B',5:'C',6:'B',7:'C'},cards=Object.values(E.IMMIGRATION_CARD_DATA);r.personal.Middle.values.prosperityStep=8;r.personal.Middle.values.prosperity=6;const keep=['mc_game_shop'],add=M.randomMarket(r,2,()=>0),n=R.applyPreparation(r,positions,{market:R.randomMarket(r),middleKeep:keep,middleMarket:add,middleSkill:'Purple',immigration:[cards[0].Working,cards[1].Working],immigrationCards:cards.slice(0,2),middleImmigrationCards:cards.slice(2,4),trade:r.trade}).records;assert.equal(n.companies.mc_game_shop.status,'market');assert.equal(n.companies.mc_training_center.status,'discarded');assert.equal(n.companies.mc_organic_farm.status,'discarded');assert.equal(n.personal.Middle.values.workerCount,14);assert.equal(n.personal.Middle.values.prosperityStep,6);assert.equal(n.personal.Middle.values.prosperity,5);assert(M.candidates(n).every(d=>!['mc_training_center','mc_organic_farm'].includes(d.id)));});
test('three-player setup has exact initial workers, separate immigration draws, individual public cards and Middle hand',()=>{const s=setup(true),r=s.records;assert.equal(s.automaMode,'Both');assert.deepEqual(r.participants,{Working:'automa',Middle:'human',Capitalist:'automa',State:'absent'});assert.equal(r.personal.Working.values.workerCount,10);assert.equal(r.personal.Middle.values.workerCount,10);assert.equal(r.personal.Middle.values.cash,40);assert.equal(r.personal.Middle.values.population,3);assert.deepEqual(r.setup.immigrationCards.map(c=>c.id),Object.keys(E.IMMIGRATION_CARD_DATA).slice(0,2));assert.deepEqual(r.setup.middleImmigrationCards.map(c=>c.id),Object.keys(E.IMMIGRATION_CARD_DATA).slice(2,4));assert.equal(r.companies.state_technical_university_init3.slots.filter(x=>x.owner==='Middle').length,3);assert.equal(r.companies.state_university_hospital_init3.slots.filter(x=>x.owner==='Working').length,3);assert.equal(r.companies.mc_doctors_office_init.slots[1].owner,'empty');assert.equal(r.companies.mc_doctors_office.status,'unbuilt');assert.equal(r.common.values.health,6);assert.equal(r.common.values.education,6);assert.equal(r.common.values.influence,4);assert.equal(r.personal.State.values.cash,120);assert.equal(P.activeOwner(s),'Middle');assert.equal(s.playerCards.classes.Middle.hand.length,7);assert.deepEqual(E.validate(JSON.parse(JSON.stringify(s))),s);});
test('Middle purchases use separate consumption stock, enforce two sources and population, and consume one hand card atomically',()=>{const s=player(setup(true)),r=s.records;r.personal.Middle.values.health=3;const before=E.copy(s),next=basic(s,{action:'BGS',resource:'health',purchases:[{source:'Middle',qty:3},{source:'State',qty:1}]});assert.equal(next.records.personal.Middle.values.health,0);assert.equal(next.records.personal.Middle.values.consumedHealth,4);assert.equal(next.records.personal.Middle.values.cash,35);assert.equal(next.playerCards.classes.Middle.hand.length,6);assert.throws(()=>basic(next,{action:'PRESSURE'}),/実行済み/);assert.throws(()=>basic(s,{action:'BGS',resource:'health',purchases:[{source:'State',qty:4}]}),/人口/);assert.throws(()=>basic(s,{action:'BGS',resource:'health',purchases:[{source:'Middle',qty:1},{source:'State',qty:1},{source:'Capitalist',qty:1}]}),/2か所/);assert.deepEqual(s,before);});
test('printed prosperity track preserves duplicate values and preparation drops two positions',()=>{const r=setup().records,m=r.personal.Middle.values;m.prosperityStep=5;m.prosperity=5;m.consumedLuxury=9;let n=M.free(r,{},{action:'USE',resource:'luxury'});assert.equal(n.personal.Middle.values.prosperityStep,6);assert.equal(n.personal.Middle.values.prosperity,5);assert.equal(n.personal.Middle.values.vp,5);n=M.free(n,{},{action:'USE',resource:'luxury'});assert.equal(n.personal.Middle.values.prosperity,6);assert.equal(n.personal.Middle.values.vp,11);n.personal.Middle.values.prosperityStep=10;n.personal.Middle.values.prosperity=7;n=M.free(n,{},{action:'USE',resource:'luxury'});assert.equal(n.personal.Middle.values.prosperityStep,10);assert.equal(n.personal.Middle.values.vp,18);assert.equal(M.final(n,{1:'C',2:'B',3:'A',4:'B',5:'C'}).stockVp,0);});
test('build may draw uncommitted workers from other companies; sale is blocked until commitments clear',()=>{let r=setup().records;r.common.unemployed.Middle.Blue=1;r.common.unemployed.Working.Gray=1;const count=r.personal.Middle.values.workerCount;r=R.validate(r);const before=E.copy(r);let n=M.basic(r,{2:'B'},{action:'BC',id:'mc_game_shop',workers:['u:Blue'],employee:'Gray',wage:'L2'});assert.equal(n.companies.mc_game_shop.operating,'yes');assert.equal(n.companies.mc_game_shop.slots[1].owner,'Working');assert.equal(n.personal.Middle.values.cash,28);assert.throws(()=>M.basic(n,{},{action:'SC',id:'mc_game_shop'}),/誓約/);n=R.applyProduction(n).records;n=M.basic(n,{},{action:'SC',id:'mc_game_shop'});assert.equal(n.companies.mc_game_shop.status,'discarded');assert.equal(n.common.unemployed.Middle.Blue,before.common.unemployed.Middle.Blue);assert.deepEqual(r,before);assert.equal(count,10);});
test('assignment closes an incomplete source, conserves workers and rejects closing with a committed colleague',()=>{let r=setup().records;const total=r.personal.Middle.values.workerCount;r.companies.mc_training_center.status='built';r.common.unemployed.Middle.Orange=1;r=R.validate(r);const plan={action:'AW',moves:[{worker:'c:state_technical_university_init3:0',companyId:'mc_training_center',index:0},{worker:'u:Orange',companyId:'mc_training_center',index:1}]};let n=M.basic(r,{2:'B'},plan);assert.equal(n.companies.state_technical_university_init3.operating,'no');assert.equal(n.companies.mc_training_center.operating,'yes');assert.equal(n.common.unemployed.Middle.Gray,r.common.unemployed.Middle.Gray+2);assert.equal(n.personal.Middle.values.workerCount,total+1);r.companies.state_technical_university_init3.slots[1].committed=true;const before=E.copy(r);assert.throws(()=>M.basic(r,{2:'B'},plan),/誓約/);assert.deepEqual(r,before);});
test('extra shift excludes committed employee bonus; capacity is eight; wages arrive before Middle pays employees',()=>{let r=setup().records,c=r.companies.mc_convenience_store_init;c.slots[1]={owner:'Working',skill:'Gray',committed:true};r.personal.Middle.values.food=7;let n=M.basic(r,{},{action:'SHIFT',id:'mc_convenience_store_init'});assert.equal(n.personal.Middle.values.food,8);assert.equal(n.personal.Middle.values.cash,40);r.personal.Middle.values.cash=0;c.slots[1].committed=false;const beforeWorking=r.personal.Working.values.cash;n=R.applyProduction(r).records;assert.equal(n.personal.Middle.values.loans,0);assert.equal(n.personal.Middle.values.cash,42);assert.equal(n.personal.Working.values.cash,beforeWorking+78);});
test('Working automa buys Middle goods and fills employee slots without moving Middle workers',()=>{let s=setup();s.card={number:'1',...WCAJudge.CARD_DATA['1']};s.records.common.values.health=0;s.records.personal.Capitalist.values.health=0;s.records.personal.Middle.values.health=3;s.records.personal.Middle.values.healthPrice=5;const buy=WCAJudge.evaluateAction(s,'BGS');assert.equal(buy.feasible,true);assert(buy.plan.purchases.some(p=>p.source==='Middle'));const cash=s.records.personal.Middle.values.cash,n=R.applyAction(s.records,buy.plan);assert(n.personal.Middle.values.cash>cash);s.records.common.unemployed.Working.Gray=2;s.records.companies.state_national_broadcaster_init3.slots.forEach(x=>x.owner='Middle');s.records.companies.state_national_broadcaster_init3.operating='yes';const aw=WCAJudge.evaluateAction(s,'AW');assert.equal(aw.feasible,true);const staffed=R.applyAction(s.records,aw.plan);assert.equal(staffed.companies.mc_convenience_store_init.slots[0].owner,'Middle');assert.equal(staffed.companies.mc_doctors_office_init.slots[0].owner,'Middle');assert.equal(staffed.companies.mc_convenience_store_init.slots[1].owner,'Working');assert.equal(staffed.companies.mc_doctors_office_init.slots[1].owner,'Working');});
test('food needs, tax, fully operational scoring and final sale-stock scoring include Middle',()=>{let r=setup().records,positions={1:'C',2:'B',3:'A',4:'B',5:'C',6:'B',7:'B'};r.personal.Middle.values.food=0;r.personal.Middle.values.consumedFood=1;r.personal.Middle.values.cash=0;let n=M.foodNeeds(r,positions,{Foreign:2});assert.equal(n.total,30);assert.equal(n.records.personal.Middle.values.cash,20);assert.equal(n.records.personal.Middle.values.loans,1);assert.equal(n.records.personal.Middle.values.consumedFood,0);const tax=R.taxPreview(r,positions,'B');assert.equal(tax.Middle.external,2);assert.equal(tax.Middle.operating,2);assert.equal(tax.Middle.income,8);assert.equal(tax.Middle.total,8+2*tax.multiplier);r.companies.mc_convenience_store_init.slots[1]={owner:'Working',skill:'Gray',committed:false};const scoring=R.applyScoring(r);assert.equal(scoring.preview.Middle.fully,1);assert.equal(scoring.records.personal.Middle.values.prosperity,1);assert.equal(scoring.records.personal.Middle.values.vp,1);r.personal.Middle.values.cash=40;r.personal.Middle.values.loans=1;r.personal.Middle.values.consumedLuxury=99;const final=M.final(r,positions);assert.equal(final.loanPenalty,3);assert.equal(final.cashVp,0);assert.equal(final.stockVp,0);assert.equal(final.policyVp,3);});
test('three-player immediate vote requires an ally and combined influence, rather than bag majority',()=>{const s=setup();s.records.personal.Working.values.influence=3;s.records.personal.Middle.values.influence=4;s.records.personal.Capitalist.values.influence=5;s.positions[1]='C';s.records.common.values.workingVotesOutside=25;assert.equal(M.immediate(s,'Working','1','B').possible,true);assert.equal(M.immediate(s,'Working','1','A').possible,false);assert.equal(WCAJudge.immediateVote2P(s,0,'1','B').possible,true);s.positions[1]='A';assert.equal(CCAJudge.immediateVote2P(s,'1','B').possible,true);});
test('Middle pending and immediate bills set aside both priority boards and resume the player after voting',()=>{let s=player(setup());s=E.reduce(s,{type:'middlePolicy',id:'1',target:'B'});assert.equal(s.records.personal.Middle.values.billMarkers,2);for(const id of ['Working','Capitalist'])assert.equal(s.automaStates[id].aside.policies['1'],'bill:Middle');s=E.reduce(s,{type:'playerEnd'});assert.equal(s.automaClass,'Capitalist');s=player(setup());s=E.reduce(s,{type:'middlePolicy',id:'4',target:'A',immediate:true});assert.equal(s.phase,'election');const sides={Working:E.automaStance(s,E.currentElection(s),'Working'),Middle:'favor',Capitalist:E.automaStance(s,E.currentElection(s),'Capitalist')};s=E.reduce(s,{type:'electionDeclare',sides,cubes:{Working:0,Middle:5,Capitalist:0}});s=E.reduce(s,{type:'electionResolve',spends:{Middle:0},autoCoinSuccesses:{Working:0,Capitalist:0}});assert.equal(s.phase,'player');assert.equal(s.middleBasicUsed,true);assert.equal(s.positions[4],'A');assert.equal(s.records.personal.Middle.values.billMarkers,3);});
test('five complete rounds alternate Working / Middle / Capitalist, replenish separately, and finish with three scores',()=>{let s=setup(true);for(let round=1;round<=5;round++){for(let turn=1;turn<=5;turn++){assert.equal(s.automaClass,'Working');assert.equal(s.turn,turn);s=working(s);assert.equal(s.phase,'player');s=basic(s,{action:'PRESSURE'});s=E.reduce(s,{type:'playerEnd'});assert.equal(s.automaClass,'Capitalist');s=checks(s);s=E.reduce(s,{type:'action',first:'no',second:'no'});}assert.equal(s.phase,'production');s=E.reduce(s,{type:'productionProduce'});s=E.reduce(s,{type:'productionNeeds',plan:R.foodNeedPlan(s.records,s.positions[6])});assert.equal(s.production.step,'middleNeeds');s=E.reduce(s,{type:'middleNeeds',plan:{Foreign:M.foodPreview(s.records,s.positions).shortage}});s=E.reduce(s,{type:'productionImf',manual:true});s=E.reduce(s,{type:'productionTaxes'});s=E.reduce(s,{type:'scoringApply'});assert.equal(s.playerCards.classes.Middle.hand.length,2);if(round<5){const before=s.records.personal.Middle.values.workerCount,keep=Object.entries(s.records.companies).filter(([id,c])=>WCA_EXTRA_COMPANIES.find(d=>d.id===id)?.class==='Middle'&&c.status==='market').map(([id])=>id);s.records.personal.Middle.values.prosperityStep=7;s.records.personal.Middle.values.prosperity=6;s=E.reduce(s,{type:'preparationApply',confirmed:true,plan:{market:R.randomMarket(s.records),middleKeep:keep,middleMarket:[],middleSkill:'White'}});assert.equal(s.records.personal.Middle.values.workerCount,before+3);assert.equal(s.records.personal.Middle.values.prosperityStep,5);assert.equal(s.records.personal.Middle.values.prosperity,5);assert.equal(s.playerCards.classes.Middle.hand.length,7);assert.equal(s.lastPreparation.middleImmigrationCards.length,1);}}assert.equal(s.phase,'gameEnd');s=E.reduce(s,{type:'gameEndApply'});assert.equal(s.phase,'finished');assert.deepEqual(Object.keys(s.finalScoring.scores).sort(),['Capitalist','Middle','Working']);assert.equal(s.playerCards.classes.Middle.discard.length,25);assert.deepEqual(E.validate(JSON.parse(JSON.stringify(s))),s);});

test('Middle initial workers stand uncommitted; later assignment commits them until production (rulebook p.10, 23)',()=>{
 const r=setup().records,initial=Object.values(r.companies).flatMap(c=>c.slots.filter(x=>x.owner==='Middle'));assert.equal(initial.length,7);assert(initial.every(x=>!x.committed));assert.equal(M.workers(r).filter(x=>x.ref.startsWith('c:')).length,7);
 r.companies.mc_training_center.status='built';r.common.unemployed.Middle.Orange=1;const n=M.basic(r,{2:'B'},{action:'AW',moves:[{worker:'c:state_technical_university_init3:0',companyId:'mc_training_center',index:0},{worker:'u:Orange',companyId:'mc_training_center',index:1}]});assert(n.companies.mc_training_center.slots.every(x=>x.owner==='Middle'&&x.committed));assert(!M.workers(n).some(x=>x.ref.startsWith('c:mc_training_center:')));assert.throws(()=>M.basic(n,{2:'B'},{action:'AW',moves:[{worker:'c:mc_training_center:0',companyId:'state_technical_university_init3',index:0}]}),/移動できない/);
 const produced=R.applyProduction(n).records;assert(produced.companies.mc_training_center.slots.every(x=>!x.committed));assert.equal(M.workers(produced).filter(x=>x.ref.startsWith('c:mc_training_center:')).length,2);
});
test('assignment candidates obey specialized slots, class, commitment and policy restrictions',()=>{
 const r=setup().records;
 for(const skill of ['Gray','Green','Blue','White','Orange','Purple'])r.common.unemployed.Middle[skill]=1;
 const choices=(id,i,reassign=true)=>M.assignmentChoices(r,id,i,reassign);
 assert.deepEqual(choices('mc_doctors_office_init',0,false).map(w=>w.skill),['White']);
 assert.deepEqual(choices('mc_convenience_store_init',0,false).map(w=>w.skill),['Green']);
 assert.deepEqual(choices('mc_doctors_office_init',1),[]);
 assert.deepEqual(choices('cc_supermarket_init',0),[]); // occupied by Working
 assert.deepEqual(choices('',0),[]);
 r.companies.cc_shopping_mall_init.slots[0].committed=true;
 assert.deepEqual(choices('cc_shopping_mall_init',0),[]);
 assert.equal(choices('cc_shopping_mall_init',1,false).length,6); // any skill in unskilled slot
 assert(choices('cc_shopping_mall_init',1).some(w=>w.ref==='c:mc_doctors_office_init:0'));
 assert(!choices('cc_shopping_mall_init',1).some(w=>w.ref==='c:cc_shopping_mall_init:0'));
 r.common.unemployed.Middle.White=0;
 assert.deepEqual(choices('mc_doctors_office_init',0,false),[]);
});
