require('../dist/companies.js');require('../dist/boards.js');require('../dist/judge.js');require('../dist/capitalist.js');require('../dist/action-card-data.js');
const P=require('../dist/player-cards.js'),E=require('../dist/engine.js'),{test}=require('node:test'),assert=require('node:assert/strict');
const keys={Working:'workingVotesOutside',Middle:'middleVotesOutside',Capitalist:'capitalistVotesOutside'};
function setup(id){const owner=id.startsWith('wc_')?'Working':'Capitalist',all=P.allCopies(owner),front=all.filter(uid=>uid.startsWith(id+'#'));const s=E.reduce(E.initial(),{type:'setup',players:2,confirmed:true,automaClass:owner==='Working'?'Capitalist':'Working',immigrant:'Gray',managePlayerCards:true,playerCardDecks:{[owner]:[...front,...all.filter(uid=>!front.includes(uid))]}});s.phase='player';s.positions[3]='B';s.positions[4]='B';s.records.personal[s.automaClass].values.influence=0;return s;}
const owner=s=>P.activeOwner(s),v=(s,id=owner(s))=>s.records.personal[id].values,play=(s,plan={})=>E.reduce(s,{type:'playerCardEffect',cardUid:s.playerCards.classes[owner(s)].hand[0],plan}),cont=(s,plan)=>E.reduce(s,{type:'playerCardContinue',plan});
function election(s,cubes){cubes??={Working:0,Middle:2,Capitalist:0,[owner(s)]:3};const proposal=E.currentElection(s),sides=Object.fromEntries(E.voters(s).map(id=>[id,id===proposal.proposer?'favor':E.automaStance(s,proposal,id)]));s=E.reduce(s,{type:'electionDeclare',sides,cubes});return E.reduce(s,{type:'electionResolve',spends:{[owner(s)]:0},autoCoinSuccesses:{Working:0,Capitalist:0}});}
function atomic(s,fn,pattern){const before=E.copy(s);assert.throws(fn,pattern);assert.deepEqual(s,before);}
const fakeDraw={Working:2,Middle:3,Capitalist:1},pollDraw={Working:1,Middle:3,Capitalist:1};
for(const id of ['wc_fake_news','cc_fake_news']){
 test(id+' freezes six revealed cubes, supports removal of all classes, and consumes one card',()=>{const s=setup(id),n=play(s,{draw:fakeDraw});for(const c of Object.keys(keys))assert.equal(n.records.common.values[keys[c]],s.records.common.values[keys[c]]+fakeDraw[c]);assert.doesNotThrow(()=>E.validate(JSON.parse(JSON.stringify(n))));atomic(n,()=>E.reduce(n,{type:'playerEnd'}),/先に完了/);atomic(n,()=>play(n),/先に完了/);atomic(n,()=>cont(n,{remove:{Working:2,Middle:3}}),/最大4/);atomic(n,()=>cont(n,{remove:{Capitalist:2}}),/不正/);const a=cont(n,{remove:{Working:1,Middle:2,Capitalist:1}});for(const [c,removed] of Object.entries({Working:1,Middle:2,Capitalist:1}))assert.equal(a.records.common.values[keys[c]],s.records.common.values[keys[c]]+removed);assert.equal(a.pendingPlayerCard,undefined);assert.equal(a.playerCards.classes[owner(a)].discard.length,1);assert.equal(a.playerCards.classes[owner(a)].hand.length,6);assert.doesNotThrow(()=>E.reduce(a,{type:'playerEnd'}));assert.equal(E.bagCount(a),E.bagCount(s)-4);});
 test(id+' may return all six to bag and fails before consumption if bag is short',()=>{let s=setup(id);const n=cont(play(s,{draw:fakeDraw}),{remove:{}});for(const key of Object.values(keys))assert.equal(n.records.common.values[key],s.records.common.values[key]);for(const key of Object.values(keys))s.records.common.values[key]=25;atomic(s,()=>play(s),/足りません/);});
}
for(const id of ['wc_interest_groups','cc_interest_groups']){
 test(id+' stops after three other-class cubes and replaces them without consuming own reveals',()=>{const s=setup(id),o=owner(s),other=o==='Working'?'Capitalist':'Working';s.records.common.values[keys.Middle]=25;s.records.common.values[keys[o]]=23;s.records.common.values[keys[other]]=22;const original=Math.random;let i=0;Math.random=()=>i++<2?(o==='Working'?0:0.999):0;let n;try{n=play(s);}finally{Math.random=original;}assert.equal(n.lastPlayerCard.politics.drawn[o],2);assert.equal(n.lastPlayerCard.politics.drawn[other],3);assert.equal(n.records.common.values[keys[o]],20);assert.equal(n.records.common.values[keys[other]],25);assert.equal(E.bagCount(n),E.bagCount(s));assert.equal(n.pendingPlayerCard,undefined);});
 test(id+' respects component supply and rejects insufficient opposing cubes atomically',()=>{const s=setup(id),o=owner(s);s.records.common.values[keys[o]]=0;const n=play(s);assert.equal(n.records.common.values[keys[o]],0);assert.equal(n.lastPlayerCard.politics.added,0);for(const c of Object.keys(keys))if(c!==o)s.records.common.values[keys[c]]=25;atomic(s,()=>play(s),/他階級/);});
}
const movements={wc_workers_movement:'2',wc_healthcare_movement:'4',wc_student_movement:'5',wc_immigration_reform:'7',cc_tap_into_new_markets:'6',cc_taxed_enough_already:'3'};
for(const [id,policy] of Object.entries(movements))test(id+' adds two cubes then submits only its specific adjacent policy',()=>{const s=setup(id);s.positions[policy]='B';const n=play(s,{id:policy,position:'A',immediate:false});assert.equal(n.proposals[policy].proposer,owner(s));assert.equal(n.records.common.values[keys[owner(s)]],s.records.common.values[keys[owner(s)]]-2);assert.equal(v(n).billMarkers,v(s).billMarkers-1);atomic(s,()=>play(s,{id:policy==='1'?'2':'1',position:'B'}),/提議できません/);atomic(s,()=>play(s,{id:policy,position:'B'}),/提議先/);const t=E.copy(s);t.positions[policy]='C';atomic(t,()=>play(t,{id:policy,position:'A'}),/提議先/);const voted=election(play(s,{id:policy,position:'A',immediate:true}));assert.equal(v(voted).influence,v(s).influence-1);assert.equal(v(voted).billMarkers,v(s).billMarkers);assert.equal(voted.positions[policy],'A');});
for(const id of ['wc_radical_reforms','cc_radical_reforms'])test(id+' proposes two sections away but forbids immediate voting',()=>{const s=setup(id);s.positions[3]='C';const n=play(s,{id:'3',position:'A'});assert.equal(n.proposals[3].target,'A');assert.equal(n.phase,'player');atomic(s,()=>play(s,{id:'3',position:'A',immediate:true}),/即時投票/);const t=E.copy(s);v(t).billMarkers=0;atomic(t,()=>play(t,{id:'3',position:'A'}),/マーカー/);});
for(const id of ['wc_need_for_change','cc_push_political_agenda']){
 test(id+' submits independent bills, pays once, waits for first election, and rejects repeating policy',()=>{const s=setup(id);s.positions[3]='B';s.positions[4]='B';v(s).influence=2;const n=play(s,{id:'3',position:'A',immediate:true});assert.equal(n.phase,'election');assert.equal(n.pendingPlayerCard.step,'firstVote');assert.equal(v(n).influence,1);assert.equal(v(n).revenue??0,(v(s).revenue??0)-(owner(s)==='Capitalist'?25:0));const a=election(n);assert.equal(a.pendingPlayerCard.step,'second');assert.equal(a.phase,'player');assert.equal(a.positions[3],'A');assert.doesNotThrow(()=>E.validate(JSON.parse(JSON.stringify(a))));atomic(a,()=>cont(a,{id:'3',position:'B'}),/異なる政策/);atomic(a,()=>E.reduce(a,{type:'playerWage'}),/先に完了/);const b=cont(a,{id:'4',position:'A',immediate:true});assert.equal(b.pendingPlayerCard.step,'finalVote');assert.equal(v(b).influence,0);const c=election(b);assert.equal(c.pendingPlayerCard,undefined);assert.equal(c.positions[4],'A');assert.equal(c.playerCards.classes[owner(c)].discard.length,1);assert.equal(v(c).billMarkers,v(s).billMarkers);});
 test(id+' also supports two deferred bills and cannot start with insufficient policies or markers',()=>{const s=setup(id);s.positions[3]='B';s.positions[4]='B';const a=play(s,{id:'3',position:'A'}),b=cont(a,{id:'4',position:'A'});assert.equal(b.pendingPlayerCard,undefined);assert.equal(Object.keys(b.proposals).length,2);assert.equal(v(b).billMarkers,1);const short=E.copy(s);v(short).billMarkers=1;v(short).influence=0;atomic(short,()=>play(short,{id:'3',position:'A'}),/足りません/);for(const policy of ['1','2','4','5','6','7'])short.proposals[policy]={proposer:owner(s),from:'B',target:'A'};atomic(short,()=>play(short,{id:'3',position:'A'}),/異なる政策/);});
}
test('political agenda borrows for mandatory cost, using revenue before capital, once',()=>{const s=setup('cc_push_political_agenda');v(s).revenue=4;v(s).capital=3;const n=play(s,{id:'3',position:'A'});assert.equal(v(n).revenue,0);assert.equal(v(n).capital,32);assert.equal(v(n).loans,1);const a=cont(n,{id:'4',position:'A'});assert.equal(v(a).capital,32);assert.equal(v(a).loans,1);});
for(const id of ['wc_public_opinion_polling','cc_public_opinion_polling']){
 test(id+' reserves five cubes, hides sides before decision, returns them if declining, keeps bill',()=>{const s=setup(id);s.positions[3]='B';const n=play(s,{id:'3',position:'A',draw:pollDraw});assert.equal(n.phase,'player');assert.equal(n.election,undefined);assert.equal(n.pendingPlayerCard.step,'poll');assert.equal(v(n).billMarkers,2);const a=cont(JSON.parse(JSON.stringify(n)),{immediate:false});assert.equal(a.pendingPlayerCard,undefined);assert.equal(a.proposals[3].target,'A');for(const key of Object.values(keys))assert.equal(a.records.common.values[key],s.records.common.values[key]);assert.equal(v(a).influence,v(s).influence);});
 test(id+' converts bill to free immediate vote, uses the same five without drawing twice, returns marker',()=>{const s=setup(id);s.positions[3]='B';v(s).influence=0;const n=play(s,{id:'3',position:'A',draw:pollDraw}),a=cont(n,{immediate:true});assert.deepEqual(a.election.reservedCubes,pollDraw);assert.equal(v(a).influence,0);assert.equal(v(a).billMarkers,2);assert.equal(a.proposals[3].target,'A');const p=E.currentElection(a),sides=Object.fromEntries(E.voters(a).map(c=>[c,c===owner(a)?'favor':E.automaStance(a,p,c)]));atomic(a,()=>E.reduce(a,{type:'electionDeclare',sides,cubes:{Working:2,Middle:2,Capitalist:1}}),/不正/);const declared=E.reduce(a,{type:'electionDeclare',sides,cubes:pollDraw});for(const key of Object.values(keys))assert.equal(declared.records.common.values[key],a.records.common.values[key]);const b=E.reduce(declared,{type:'electionResolve',spends:{[owner(s)]:0},autoCoinSuccesses:{Working:0,Capitalist:0}});assert.equal(b.pendingPlayerCard,undefined);assert.equal(b.positions[3],'A');assert.equal(v(b).vp,3);assert.equal(v(b).billMarkers,3);assert.equal(b.records.common.values[keys.Middle],s.records.common.values[keys.Middle]+3);for(const c of ['Working','Capitalist'])assert.equal(b.records.common.values[keys[c]],s.records.common.values[keys[c]]+(sides[c]==='favor'?1:0));assert.equal(b.playerCards.classes[owner(s)].discard.length,1);});
 test(id+' rejects corrupt persisted disclosure and blocked actions',()=>{const s=setup(id),n=play(s,{id:'3',position:'A',draw:pollDraw});atomic(n,()=>E.reduce(n,{type:'playerEnd'}),/先に完了/);const bad=E.copy(n);bad.pendingPlayerCard.drawn.Working=5;assert.throws(()=>E.validate(bad),/投票駒/);const a=cont(n,{immediate:true}),corrupt=E.copy(a);corrupt.election.reservedCubes.Middle=0;assert.throws(()=>E.validate(corrupt),/投票駒/);});
}
test('polling defeat returns its marker and restores policy priority for another immediate proposal',()=>{const s=setup('wc_public_opinion_polling'),before=E.copy(s.policies),draw={Working:0,Middle:2,Capitalist:3},a=cont(play(s,{id:'3',position:'A',draw}),{immediate:true}),proposal=E.currentElection(a);assert.deepEqual(a.policies,before);const d=E.reduce(a,{type:'electionDeclare',sides:{Working:'favor',Capitalist:E.automaStance(a,proposal,'Capitalist')},cubes:draw});const b=E.reduce(d,{type:'electionResolve',spends:{Working:0},autoCoinSuccesses:{Capitalist:0}});assert.equal(b.positions[3],'B');assert.equal(b.lastElection.passed,false);assert.equal(v(b).vp,0);assert.equal(v(b).billMarkers,3);assert.equal(b.proposals[3],undefined);assert.deepEqual(b.policies,before);assert(E.politicalOptions(b,'Working','wc_need_for_change').includes('3'));});
test('polling does not refill or reroll a reserved draw even with fewer than five cubes left in bag',()=>{const s=setup('wc_public_opinion_polling');for(const key of Object.values(keys))s.records.common.values[key]=25;s.records.common.values[keys.Working]=20;const draw={Working:5,Middle:0,Capitalist:0},a=cont(play(s,{id:'3',position:'A',draw}),{immediate:true});assert.equal(E.bagCount(a),0);const b=election(a,draw);assert.equal(b.positions[3],'A');assert.equal(E.bagCount(b),0);assert.equal(v(b).billMarkers,3);});
