require('../dist/companies.js');require('../dist/boards.js');require('../dist/judge.js');require('../dist/capitalist.js');require('../dist/action-card-data.js');
const P=require('../dist/player-cards.js'),E=require('../dist/engine.js'),{test}=require('node:test'),assert=require('node:assert/strict');
function setup(owner='Capitalist'){const id=owner==='Capitalist'?'cc_extra_shift':'wc_public_sector_overtime',all=P.allCopies(owner),front=all.filter(uid=>uid.startsWith(id+'#')),s=E.reduce(E.initial(),{type:'setup',players:2,automaClass:owner==='Capitalist'?'Working':'Capitalist',confirmed:true,immigrant:'Gray',managePlayerCards:true,playerCardDecks:{[owner]:[...front,...all.filter(uid=>!front.includes(uid))]}});s.phase='player';return s;}
const play=(s,companyId,qty)=>E.reduce(s,{type:'playerCardEffect',cardUid:s.playerCards.classes[P.activeOwner(s)].hand[0],plan:{companyId,...(qty===undefined?{}:{qty})}});
const v=(s,id)=>s.records.personal[id].values;
test('extra shift pays and produces only the selected company; no round-end cleanup or union income',()=>{const s=setup();s.records.companies.cc_supermarket_init.slots[0].committed=true;s.records.companies.cc_shopping_mall_init.strike=true;s.records.personal.Working.unions.Food=true;const before=E.copy(s),n=play(s,'cc_supermarket_init');assert.equal(v(n,'Capitalist').revenue,100);assert.equal(v(n,'Capitalist').food,5);assert.equal(v(n,'Capitalist').luxury,2);assert.equal(v(n,'Working').cash,50);assert.equal(v(n,'Working').influence,v(s,'Working').influence);assert.equal(v(n,'State').cash,120);assert.equal(n.records.companies.cc_supermarket_init.slots[0].committed,true);assert.equal(n.records.companies.cc_shopping_mall_init.strike,true);assert.equal(n.phase,'player');assert.equal(n.production,undefined);assert.equal(n.playerCards.classes.Capitalist.hand.length,6);assert.equal(n.playerCards.used,true);assert.deepEqual(s,before);assert.throws(()=>play(n,'cc_supermarket_init'),/実行/);});
test('extra shift includes machinery and pays Revenue then Capital then mandatory loans',()=>{const s=setup();s.records.companies.cc_shopping_mall_init.machinery=true;v(s,'Capitalist').revenue=3;v(s,'Capitalist').capital=4;const n=play(s,'cc_shopping_mall_init'),d=P.companyDefinition(s.records,'cc_shopping_mall_init');assert.equal(n.lastPlayerCard.production.amount,d.production.amount+d.production.machinery_bonus);assert.equal(v(n,'Capitalist').revenue,0);assert.equal(v(n,'Capitalist').capital,37);assert.equal(v(n,'Capitalist').loans,1);});
test('storage overflow uses free trade and reports discarded goods without buying human storage',()=>{const s=setup();v(s,'Capitalist').food=7;v(s,'Capitalist').freeTradeFood=7;const n=play(s,'cc_supermarket_init');assert.equal(v(n,'Capitalist').food,8);assert.equal(v(n,'Capitalist').freeTradeFood,8);assert.equal(n.lastPlayerCard.production.storage.lost,2);assert.equal(v(n,'Capitalist').foodStorage,0);assert.equal(v(n,'Capitalist').revenue,100);});
test('extra shift rejects wrong owner, automation, inactive, strike and unknown records atomically',()=>{for(const change of [s=>{s.records.companies.cc_supermarket_init.operating='no';},s=>{s.records.companies.cc_supermarket_init.strike=true;},s=>{s.records.companies.cc_supermarket_init.wage='unknown';},s=>{v(s,'Capitalist').food=null;},s=>{v(s,'Working').cash=null;}]){const s=setup();change(s);const before=E.copy(s);assert.throws(()=>play(s,'cc_supermarket_init'));assert.deepEqual(s,before);}const s=setup();assert.throws(()=>play(s,'state_public_hospital_init'),/自分/);const c=s.records.companies.cc_electronics_auto;c.status='built';c.operating='yes';assert.throws(()=>play(s,'cc_electronics_auto'),/自動化/);});
test('L3 strike permits production while preserving its token',()=>{const s=setup(),c=s.records.companies.cc_supermarket_init;c.wage='L3';c.strike=true;const n=play(s,'cc_supermarket_init');assert.equal(v(n,'Capitalist').food,5);assert.equal(n.records.companies.cc_supermarket_init.strike,true);assert.equal(v(n,'Working').cash,30+P.companyDefinition(s.records,'cc_supermarket_init').wages.L3);});
test('public overtime pays State wages and caps public stock, then buys matching output',()=>{const s=setup('Working');s.records.companies.state_public_hospital_init.slots[0].committed=true;v(s,'State').cash=0;s.records.common.values.health=9;const n=play(s,'state_public_hospital_init',2);assert.equal(v(n,'State').loans,1);assert.equal(v(n,'State').cash,40);assert.equal(v(n,'Working').cash,40);assert.equal(v(n,'Working').health,2);assert.equal(n.records.common.values.health,8);assert.equal(n.records.common.values.education,5);assert.equal(v(n,'Capitalist').food,1);assert.equal(n.records.companies.state_public_hospital_init.slots[0].committed,true);assert.equal(n.playerCards.classes.Working.hand.length,6);assert.equal(n.workingBasicUsed,true);});
test('public overtime can skip purchases and apply education prices A/B/C after wages',()=>{for(const [policy,price] of [['A',0],['B',5],['C',10]]){const s=setup('Working');s.positions[5]=policy;const n=play(s,'state_public_university_init',3);assert.equal(v(n,'Working').cash,50-price*3);assert.equal(v(n,'Working').education,3);assert.equal(v(n,'State').cash,100+price*3);}const s=setup('Working'),n=play(s,'state_public_university_init');assert.equal(v(n,'Working').cash,50);assert.equal(n.records.common.values.education,9);});
test('public overtime can buy media Influence for 5V per unit',()=>{const s=setup('Working'),id='state_local_tv_init',c=s.records.companies[id];c.operating='yes';c.slots=c.slots.map((slot,index)=>({owner:'Working',skill:index===0?'Purple':'Gray',committed:true}));const d=P.companyDefinition(s.records,id),n=play(s,id,2);assert.equal(v(n,'Working').influence,v(s,'Working').influence+2);assert.equal(v(n,'Working').cash,30+d.wages.L2-10);assert.equal(n.records.common.values.influence,s.records.common.values.influence+d.production.amount-2);});
test('invalid overtime purchase or company rolls back wages, stock and card together',()=>{for(const qty of [-1,1.5,4,20]){const s=setup('Working'),before=E.copy(s);assert.throws(()=>play(s,'state_public_hospital_init',qty),/整数|人口/);assert.deepEqual(s,before);}const s=setup('Working');assert.throws(()=>play(s,'cc_supermarket_init'),/公共/);s.records.companies.state_public_hospital_init.strike=true;assert.throws(()=>play(s,'state_public_hospital_init'),/ストライキ/);s.records.common.values.health=null;assert.throws(()=>play(s,'state_public_hospital_init'));});
