require('../dist/companies.js');require('../dist/boards.js');require('../dist/judge.js');require('../dist/capitalist.js');require('../dist/action-card-data.js');
const P=require('../dist/player-cards.js'),E=require('../dist/engine.js'),{test}=require('node:test'),assert=require('node:assert/strict');
function setup(id='cc_global_branding'){const all=P.allCopies('Capitalist'),front=all.filter(uid=>uid.startsWith(id+'#')),s=E.reduce(E.initial(),{type:'setup',players:2,automaClass:'Working',confirmed:true,immigrant:'Gray',managePlayerCards:true,playerCardDecks:{Capitalist:[...front,...all.filter(uid=>!front.includes(uid))]},tradeDecks:{export:Object.keys(E.EXPORT_CARD_DATA),business:Object.keys(E.BUSINESS_DEAL_DATA)}});s.phase='player';s.records.trade.exportCard={name:'test',offers:[{resource:'food',quantity:2,revenue:25},{resource:'luxury',quantity:3,revenue:30},{resource:'health',quantity:2,revenue:20}]};return s;}
const play=(s,plan)=>E.reduce(s,{type:'playerCardEffect',cardUid:s.playerCards.classes.Capitalist.hand[0],plan});
const cap=s=>s.records.personal.Capitalist.values;
const reveal=s=>E.reduce(s,{type:'playerCardReveal',cardUid:s.playerCards.classes.Capitalist.hand[0]});
const finish=(s,plan)=>E.reduce(s,{type:'playerCardContinue',plan});
test('branding executes printed transactions and extra Luxury once, consuming one action card and FTZ first',()=>{const s=setup();cap(s).food=1;cap(s).freeTradeFood=1;cap(s).luxury=5;cap(s).freeTradeLuxury=4;const before=E.copy(s),n=play(s,{transactions:[0,1],qty:6});assert.equal(cap(n).revenue,235);assert.equal(cap(n).food,0);assert.equal(cap(n).freeTradeFood,0);assert.equal(cap(n).luxury,0);assert.equal(cap(n).freeTradeLuxury,0);assert.equal(n.playerCards.classes.Capitalist.discard.length,1);assert.equal(cap(n).vp,0);assert.deepEqual(s,before);});
test('food crisis pays 15 for up to four food in addition to printed offers',()=>{const s=setup('cc_global_food_crisis');cap(s).food=6;const n=play(s,{transactions:[0],qty:4});assert.equal(cap(n).food,0);assert.equal(cap(n).revenue,205);assert.throws(()=>play(s,{transactions:[],qty:5}),/上限/);assert.equal(play(s,{transactions:[],qty:4}).records.personal.Capitalist.values.revenue,180);});
test('bonus export failure rolls back earlier exports, funds and hand',()=>{const s=setup();cap(s).food=2;cap(s).luxury=3;for(const plan of [{transactions:[0,1],qty:1},{transactions:[0,0],qty:0},{transactions:[4],qty:0},{transactions:[],qty:7},{transactions:[],qty:0},{transactions:[],qty:-1}]){const before=E.copy(s);assert.throws(()=>play(s,plan));assert.deepEqual(s,before);}});
test('foreign partner purchases a Business Deal before exporting Food and Luxury from FTZ',()=>{const s=setup('cc_foreign_partner');s.records.trade.businessDeals=[{name:'deal',food:2,luxury:3,cost:20,tariffB:5,tariffA:10}];const n=play(s,{dealIndex:0,destination:'freeTrade',transactions:[0,1]});assert.equal(cap(n).revenue,155);assert.equal(cap(n).food,1);assert.equal(cap(n).luxury,2);assert.equal(cap(n).freeTradeFood,0);assert.equal(cap(n).freeTradeLuxury,0);assert.equal(n.records.trade.businessDeals.length,0);assert.equal(n.records.personal.State.values.cash,120);assert.equal(n.playerCards.classes.Capitalist.discard.length,1);});
test('foreign partner normal storage pays policy B tariff; C pays none and limits storage before exporting',()=>{for(const [policy,tariff] of [['B',5],['C',0]]){const s=setup('cc_foreign_partner');s.positions[6]=policy;s.records.trade.businessDeals=[{name:'deal',food:2,luxury:3,cost:20}];const n=play(s,{dealIndex:0,destination:'regular',transactions:[]});assert.equal(cap(n).revenue,100-tariff);assert.equal(n.records.personal.State.values.cash,120+tariff);assert.equal(cap(n).food,3);assert.equal(cap(n).luxury,5);}const s=setup('cc_foreign_partner');cap(s).freeTradeFood=7;cap(s).freeTradeLuxury=12;s.records.trade.businessDeals=[{name:'deal',food:2,luxury:3,cost:20}];const n=play(s,{dealIndex:0,destination:'freeTrade',transactions:[]});assert.deepEqual(n.lastPlayerCard.tradeEffect.losses,{food:1,luxury:3});assert.equal(cap(n).freeTradeFood,8);});
test('foreign partner rejects wrong policy, medical exports, invalid deal or storage; fails atomically after purchase',()=>{const s=setup('cc_foreign_partner');s.records.trade.businessDeals=[{name:'deal',food:2,luxury:0,cost:20}];for(const p of [{dealIndex:0,destination:'regular',transactions:[2]},{dealIndex:0,destination:'freeTrade',transactions:[1]},{dealIndex:1,destination:'regular',transactions:[]},{dealIndex:0,destination:'bad',transactions:[]}]){const before=E.copy(s);assert.throws(()=>play(s,p));assert.deepEqual(s,before);}s.positions[6]='A';assert.throws(()=>play(s,{dealIndex:0,destination:'regular',transactions:[]}),/政策6/);});
test('foreign partner borrows for the full purchase before sale proceeds arrive',()=>{const s=setup('cc_foreign_partner');cap(s).revenue=0;cap(s).capital=0;s.records.trade.businessDeals=[{name:'deal',food:2,luxury:0,cost:20}];const n=play(s,{dealIndex:0,destination:'freeTrade',transactions:[0]});assert.equal(cap(n).loans,1);assert.equal(cap(n).capital,30);assert.equal(cap(n).revenue,25);});
test('insight reveals next two exports, consumes one card, preserves Business deck and saves a pending effect',()=>{const s=setup('cc_foreign_market_insight'),before=E.copy(s),n=reveal(s);assert.deepEqual(n.pendingPlayerCard.revealed,[E.EXPORT_CARD_DATA.E02,E.EXPORT_CARD_DATA.E03]);assert.deepEqual(n.tradeDecks.business,s.tradeDecks.business);assert.equal(n.playerCards.classes.Capitalist.hand.length,6);assert.equal(n.playerCards.used,true);assert.deepEqual(n.records.trade,s.records.trade);assert.doesNotThrow(()=>E.validate(JSON.parse(JSON.stringify(n))));assert.throws(()=>E.reduce(n,{type:'playerEnd'}),/先に完了/);assert.throws(()=>E.reduce(n,{type:'playerWage',id:'cc_supermarket_init',wage:'L3'}),/先に完了/);assert.deepEqual(s,before);});
test('insight exchange uses chosen printed offer, keeps deck draw fixed and does not discard a second action card',()=>{const s=reveal(setup('cc_foreign_market_insight')),o=s.pendingPlayerCard.revealed[1].offers[0];cap(s).food=o.quantity;const deck=[...s.tradeDecks.export],n=finish(s,{choice:1,transactions:[0]});assert.deepEqual(n.records.trade.exportCard.offers,E.EXPORT_CARD_DATA.E03.offers);assert.equal(cap(n).revenue,120+o.revenue);assert.equal(n.pendingPlayerCard,undefined);assert.equal(n.playerCards.classes.Capitalist.discard.length,1);assert.deepEqual(n.tradeDecks.export,deck);assert.throws(()=>finish(n,{choice:0,transactions:[]}),/継続中/);});
test('insight may keep current card and discard both reveals, and failures preserve the pending choice and deck',()=>{const s=reveal(setup('cc_foreign_market_insight'));cap(s).food=2;const n=finish(s,{choice:-1,transactions:[0]});assert.equal(n.records.trade.exportCard.name,'test');assert.equal(n.lastPlayerCard.tradeEffect.choice,-1);for(const plan of [{choice:2,transactions:[]},{choice:0,transactions:[99]},{choice:0,transactions:[1]}]){const before=E.copy(s);assert.throws(()=>finish(s,plan));assert.deepEqual(s,before);}const t=E.copy(s);t.pendingPlayerCard.revealed[0].offers[0].revenue=999;assert.throws(()=>E.validate(t),/公開が不正/);assert.throws(()=>finish(t,{choice:0,transactions:[]}),/公開が不正/);const legacy=E.copy(s);delete legacy.playerCards;assert.throws(()=>E.validate(legacy),/手札管理/);});
test('normal player export also draws from FTZ before normal storage',()=>{const s=setup();cap(s).food=0;cap(s).freeTradeFood=2;const n=E.reduce(s,{type:'playerExport',cardUid:s.playerCards.classes.Capitalist.hand[0],transactions:[0]});assert.equal(cap(n).freeTradeFood,0);assert.equal(cap(n).revenue,145);});
