require('../dist/companies.js');require('../dist/boards.js');require('../dist/judge.js');require('../dist/capitalist.js');require('../dist/action-card-data.js');
const P=require('../dist/player-cards.js'),E=require('../dist/engine.js'),{test}=require('node:test'),assert=require('node:assert/strict');
function setup(owner='Capitalist'){const id=owner==='Capitalist'?'cc_business_expansion':'wc_general_strike',all=P.allCopies(owner),front=all.filter(uid=>uid.startsWith(id+'#')),s=E.reduce(E.initial(),{type:'setup',players:2,automaClass:owner==='Capitalist'?'Working':'Capitalist',confirmed:true,immigrant:'Gray',managePlayerCards:true,playerCardDecks:{[owner]:[...front,...all.filter(uid=>!front.includes(uid))]}});s.phase='player';return s;}
const play=(s,plan)=>E.reduce(s,{type:'playerCardEffect',cardUid:s.playerCards.classes[P.activeOwner(s)].hand[0],plan});
const v=(s,id)=>s.records.personal[id].values;
function company(s,id,status='market'){const d=P.companyDefinition(s.records,id);s.records.companies[id]={status,wage:d.workers.length?'L2':'unknown',operating:status==='built'?'yes':'no',machinery:false,strike:false,note:'',slots:d.workers.map(req=>({owner:status==='built'?'Working':'empty',skill:req.color,committed:false}))};return s.records.companies[id];}
const build=(companyId,workers=[],wage='L2')=>({companyId,workers,wage});
function plan(s,builds=[build('cc_vegetable_farm'),build('cc_clinic_pool')]){return {builds,marketAdds:WCARecords.marketCandidates(s.records).slice(0,2).map(d=>d.id)};}
function expansion(){const s=setup();company(s,'cc_vegetable_farm');company(s,'cc_clinic_pool');return s;}
test('business expansion builds two distinct companies at full price and then refills two cards',()=>{const s=expansion(),p=plan(s),before=E.copy(s),n=play(s,p),cost=p.builds.reduce((sum,b)=>sum+P.companyDefinition(s.records,b.companyId).cost,0);assert.equal(v(n,'Capitalist').revenue,120-cost);assert.equal(v(n,'State').cash,120);for(const id of p.builds.map(b=>b.companyId)){assert.equal(n.records.companies[id].status,'built');assert.equal(n.records.companies[id].operating,'no');}for(const id of p.marketAdds)assert.equal(n.records.companies[id].status,'market');assert.equal(n.playerCards.classes.Capitalist.hand.length,6);assert.equal(n.playerCards.classes.Capitalist.discard.length,1);assert.deepEqual(s,before);});
test('business expansion staffs both companies using a shared unemployment pool and commits workers',()=>{const s=expansion();s.records.common.unemployed.Working={Gray:2,Green:1,White:1,Blue:0,Orange:0,Purple:0};const n=play(s,plan(s,[build('cc_vegetable_farm',['Green','Gray']),build('cc_clinic_pool',['White','Gray'],'L3')]));assert(n.records.companies.cc_vegetable_farm.slots.every(slot=>slot.committed));assert(n.records.companies.cc_clinic_pool.slots.every(slot=>slot.committed));assert.equal(n.records.companies.cc_clinic_pool.wage,'L3');assert.equal(n.records.common.unemployed.Working.Gray,0);});
test('business expansion supports automation and borrowing without State contribution',()=>{const s=expansion();company(s,'cc_electronics_auto');v(s,'Capitalist').revenue=0;v(s,'Capitalist').capital=0;const p=plan(s,[build('cc_electronics_auto'),build('cc_clinic_pool')]),n=play(s,p),cost=p.builds.reduce((sum,b)=>sum+P.companyDefinition(s.records,b.companyId).cost,0);assert.equal(n.records.companies.cc_electronics_auto.operating,'yes');assert.equal(v(n,'Capitalist').loans,Math.ceil(cost/50));assert.equal(v(n,'Capitalist').capital,Math.ceil(cost/50)*50-cost);assert.equal(v(n,'State').loans,0);});
test('business expansion second-build failure rolls back the first build, cost, staff and card',()=>{const s=expansion();s.records.common.unemployed.Working.Green=1;s.records.common.unemployed.Working.White=1;s.records.common.unemployed.Working.Gray=1;const before=E.copy(s);assert.throws(()=>play(s,plan(s,[build('cc_vegetable_farm',['Green','Gray']),build('cc_clinic_pool',['White','Gray'])])),/足りません/);assert.deepEqual(s,before);});
test('business expansion rejects duplicate or fewer builds, nonmarket and premature use of refill cards',()=>{const s=expansion(),p=plan(s);for(const builds of [[p.builds[0]],[p.builds[0],p.builds[0]],[p.builds[0],build(p.marketAdds[0])],[p.builds[0],build('state_public_hospital_init')]]){const before=E.copy(s);assert.throws(()=>play(s,{...p,builds}));assert.deepEqual(s,before);}});
test('business expansion enforces minimum wage, full staffing and Gray priority',()=>{const s=expansion();s.positions[2]='A';assert.throws(()=>play(s,plan(s)),/最低賃金/);s.positions[2]='B';s.records.common.unemployed.Working.Green=1;s.records.common.unemployed.Working.White=2;assert.throws(()=>play(s,plan(s,[build('cc_vegetable_farm',['Green']),build('cc_clinic_pool')])),/全スロット/);assert.throws(()=>play(s,plan(s,[build('cc_vegetable_farm',['Green','White']),build('cc_clinic_pool')])),/未熟練失業者を優先/);});
test('business expansion respects the 12-company cap across both builds',()=>{const s=expansion();for(const d of WCARecords.marketCandidates(s.records).slice(0,7))company(s,d.id,'built');assert.equal(Object.entries(s.records.companies).filter(([id,c])=>c.status==='built'&&P.companyDefinition(s.records,id).class==='Capitalist').length,11);const before=E.copy(s);assert.throws(()=>play(s,plan(s)),/12社/);assert.deepEqual(s,before);});
test('refill excludes initial, discarded, built, market and duplicate cards; handles 0 or 1 remaining',()=>{const s=expansion(),p=plan(s);for(const marketAdds of [[p.marketAdds[0],p.marketAdds[0]],['cc_supermarket_init',p.marketAdds[0]],['cc_vegetable_farm',p.marketAdds[0]],[]])assert.throws(()=>play(s,{...p,marketAdds}),/補充/);for(const count of [0,1]){const t=expansion(),available=WCARecords.marketCandidates(t.records);available.slice(count).forEach(d=>t.records.companies[d.id].status='discarded');const q=plan(t),n=play(t,q);assert.equal(q.marketAdds.length,count);for(const id of q.marketAdds)assert.equal(n.records.companies[id].status,'market');}});
test('general strike places up to two plus active unions and commits only selected workers',()=>{const s=setup('Working');company(s,'cc_vegetable_farm','built');s.records.personal.Working.unions.Food=true;const ids=['cc_supermarket_init','cc_shopping_mall_init','cc_vegetable_farm'],before=E.copy(s),n=play(s,{companyIds:ids});for(const id of ids){assert.equal(n.records.companies[id].strike,true);assert(n.records.companies[id].slots.every(slot=>slot.committed));}assert.equal(n.records.companies.state_public_hospital_init.strike,false);assert.equal(n.playerCards.classes.Working.discard.length,1);assert.equal(n.workingBasicUsed,true);assert.equal(v(n,'Working').cash,30);assert.deepEqual(s,before);assert.throws(()=>play(setup('Working'),{companyIds:ids}),/1〜2社/);});
test('general strike rejects policy A, empty or duplicate targets and ineligible companies atomically',()=>{for(const mutate of [s=>s.positions[2]='A',s=>s.records.companies.cc_shopping_mall_init.slots[0].committed=true,s=>s.records.companies.cc_shopping_mall_init.wage='L3',s=>s.records.companies.cc_shopping_mall_init.strike=true]){const s=setup('Working');mutate(s);const before=E.copy(s);assert.throws(()=>play(s,{companyIds:['cc_supermarket_init','cc_shopping_mall_init']}));assert.deepEqual(s,before);}const s=setup('Working');for(const companyIds of [[],['cc_supermarket_init','cc_supermarket_init'],['cc_supermarket_init','state_public_hospital_init']])assert.throws(()=>play(s,{companyIds}));});
test('general strike cannot exceed seven tokens and integrates with automa wage response and production',()=>{const s=setup('Working');for(const d of WCARecords.marketCandidates(s.records).slice(0,6))company(s,d.id,'built').strike=true;const before=E.copy(s);assert.throws(()=>play(s,{companyIds:['cc_supermarket_init','cc_shopping_mall_init']}),/7枚/);assert.deepEqual(s,before);let n=play(s,{companyIds:['cc_supermarket_init']});assert.equal(Object.values(n.records.companies).filter(c=>c.strike).length,7);n.turn=5;n=E.reduce(n,{type:'playerEnd'});n.phase='action';n=E.reduce(n,{type:'action',first:'no',second:'no'});assert.equal(n.phase,'production');assert(n.production.wageDraws.some(draw=>draw.id==='cc_supermarket_init'));n=E.reduce(n,{type:'productionProduce'});assert(Object.values(n.records.companies).every(c=>!c.strike));});
