require('../dist/companies.js');require('../dist/boards.js');require('../dist/judge.js');require('../dist/capitalist.js');require('../dist/action-card-data.js');
const P=require('../dist/player-cards.js'),E=require('../dist/engine.js'),{test}=require('node:test'),assert=require('node:assert/strict');
function setup(id='cc_investment_opportunities'){const all=P.allCopies('Capitalist'),front=all.filter(uid=>uid.startsWith(id+'#')),s=E.reduce(E.initial(),{type:'setup',players:2,automaClass:'Working',confirmed:true,immigrant:'Gray',managePlayerCards:true,playerCardDecks:{Capitalist:[...front,...all.filter(uid=>!front.includes(uid))]}});s.phase='player';return s;}
const play=(s,plan)=>E.reduce(s,{type:'playerCardEffect',cardUid:s.playerCards.classes.Capitalist.hand[0],plan});
const v=(s,id='Capitalist')=>s.records.personal[id].values;
const build=(companyId,mode='discount',workers=[],wage='L2')=>({companyId,mode,workers,wage});
function market(s,id){s.records.companies[id].status='market';}
function tech(){return setup('cc_technological_progress');}
test('investment discounts a market company by 10 and preserves unrelated market cards and State',()=>{const s=setup(),id='cc_clinic_pool';market(s,id);const before=E.copy(s),cost=P.companyDefinition(s.records,id).cost,n=play(s,build(id));assert.equal(v(n).revenue,120-cost+10);assert.equal(n.records.companies[id].status,'built');assert.equal(n.records.companies[id].operating,'no');assert.equal(v(n,'State').cash,120);assert.equal(n.playerCards.classes.Capitalist.discard.length,1);assert.equal(n.lastPlayerCard.companySearch,null);for(const [other,c] of Object.entries(s.records.companies))if(other!==id)assert.deepEqual(n.records.companies[other],c);assert.deepEqual(s,before);});
test('investment searches only undealt companies, pays 10 extra, and excludes selected company from future draws',()=>{const s=setup(),id=WCARecords.marketCandidates(s.records)[0].id,before=E.copy(s),n=play(s,build(id,'search'));assert.equal(v(n).revenue,120-P.companyDefinition(s.records,id).cost-10);assert.equal(n.records.companies[id].status,'built');assert.deepEqual(n.lastPlayerCard.companySearch,{companyId:id,shuffleRequired:true});assert(!WCARecords.marketCandidates(n.records).some(d=>d.id===id));assert(!WCARecords.randomMarket(n.records,100,()=>0).includes(id));assert.deepEqual(s,before);});
test('investment staffing uses ordinary skills, unemployment, Gray priority and minimum wage',()=>{const s=setup(),id='cc_clinic_pool';market(s,id);s.records.common.unemployed.Working.White=1;const n=play(s,build(id,'discount',['White','Gray'],'L3'));assert.equal(n.records.companies[id].operating,'yes');assert.equal(n.records.companies[id].wage,'L3');assert(n.records.companies[id].slots.every(slot=>slot.committed));assert.equal(n.records.common.unemployed.Working.White,0);assert.throws(()=>play(s,build(id,'discount',['White'])),/全スロット/);assert.throws(()=>play(s,build(id,'discount',['Gray','Gray'])),/技能/);s.positions[2]='A';assert.throws(()=>play(s,build(id)),/最低賃金/);});
test('investment automates workerless companies and borrows from Revenue then Capital with premium included',()=>{const s=setup(),id='cc_electronics_auto';s.records.companies[id].status='unbuilt';v(s).revenue=2;v(s).capital=3;const cost=P.companyDefinition(s.records,id).cost+10,n=play(s,build(id,'search'));assert.equal(n.records.companies[id].operating,'yes');assert.equal(n.records.companies[id].wage,'unknown');assert.equal(v(n).revenue,0);assert.equal(v(n).capital,55-cost);assert.equal(v(n).loans,1);assert.equal(v(n,'State').cash,120);});
test('investment rejects invalid mode, wrong pool, initial or discarded companies and unknown money atomically',()=>{const s=setup(),id='cc_clinic_pool';market(s,id);for(const p of [build(id,'bad'),build(id,'search'),build('cc_supermarket_init','search'),build('state_public_hospital_init','search')]){const before=E.copy(s);assert.throws(()=>play(s,p));assert.deepEqual(s,before);}s.records.companies[id].status='discarded';assert.throws(()=>play(s,build(id,'search')),/企業山札/);s.records.companies[id].status='unbuilt';v(s).capital=null;const before=E.copy(s);assert.throws(()=>play(s,build(id,'search')),/未確認/);assert.deepEqual(s,before);});
test('investment checks the 12-company cap without charging the premium or changing deck membership',()=>{const s=setup(),defs=WCARecords.marketCandidates(s.records);defs.slice(0,8).forEach(d=>{const c=s.records.companies[d.id];c.status='built';c.operating='no';});const id=defs[8].id,before=E.copy(s);assert.throws(()=>play(s,build(id,'search')),/12社/);assert.deepEqual(s,before);});
test('technology costs 20 or 45, sets one token per selected company and changes production without wage changes',()=>{for(const [qty,cost,ids] of [[1,20,['cc_shopping_mall_init']],[2,45,['cc_shopping_mall_init','cc_clinic_init']]]){const s=tech();if(ids.includes('cc_clinic_init')){const c=s.records.companies.cc_clinic_init;c.operating='yes';c.slots=c.slots.map((slot,index)=>({owner:'Working',skill:index===0?'White':'Gray',committed:false}));}const before=E.copy(s),n=play(s,{qty,companyIds:ids});assert.equal(v(n).revenue,120-cost);assert.equal(v(n,'State').cash,120);assert.deepEqual(n.lastPlayerCard.machinery,{quantity:qty,placed:qty,lost:0,cost});for(const id of ids){assert.equal(n.records.companies[id].machinery,true);assert.equal(n.records.companies[id].wage,s.records.companies[id].wage);assert.deepEqual(n.records.companies[id].slots,s.records.companies[id].slots);const output=WCARecords.productionPreview(n.records).items.find(item=>item.id===id),old=WCARecords.productionPreview(s.records).items.find(item=>item.id===id);assert.equal(output.amount,old.amount+P.companyDefinition(s.records,id).production.machinery_bonus);assert.equal(output.wage,old.wage);}assert.deepEqual(s,before);}});
test('technology may mechanize inactive companies but does not make them produce',()=>{const s=tech(),id='cc_shopping_mall_init';s.records.companies[id].operating='no';const n=play(s,{qty:1,companyIds:[id]});assert.equal(n.records.companies[id].operating,'no');assert.equal(WCARecords.productionPreview(n.records).items.find(item=>item.id===id).amount,0);});
test('technology enforces available tokens, distinct eligible own companies, and exact requested placements',()=>{const s=tech();for(const plan of [{qty:0,companyIds:[]},{qty:3,companyIds:[]},{qty:2,companyIds:['cc_shopping_mall_init','cc_shopping_mall_init']},{qty:1,companyIds:['cc_supermarket_init']},{qty:1,companyIds:['state_public_hospital_init']},{qty:1,companyIds:[]},{qty:2,companyIds:['cc_shopping_mall_init']}]){const before=E.copy(s);assert.throws(()=>play(s,plan));assert.deepEqual(s,before);}s.records.companies.cc_shopping_mall_init.machinery=true;assert.throws(()=>play(s,{qty:1,companyIds:['cc_shopping_mall_init']}));const defs=WCARecords.marketCandidates(s.records).filter(d=>d.production.machinery_bonus);for(const d of defs.slice(0,4)){s.records.companies[d.id].status='built';s.records.companies[d.id].machinery=true;}s.records.companies.cc_clinic_init.machinery=true;const before=E.copy(s);assert.throws(()=>play(s,{qty:1,companyIds:['cc_college_init']}),/残り枚数/);assert.deepEqual(s,before);});
test('technology loses excess tokens only when no eligible placement remains, still charging printed cost',()=>{const s=tech();for(const [id,c] of Object.entries(s.records.companies))if(id!=='cc_shopping_mall_init'&&P.companyDefinition(s.records,id).production.machinery_bonus)c.status='unbuilt';const n=play(s,{qty:2,companyIds:['cc_shopping_mall_init']});assert.equal(v(n).revenue,75);assert.equal(n.lastPlayerCard.machinery.lost,1);s.records.companies.cc_shopping_mall_init.machinery=true;const m=play(s,{qty:1,companyIds:[]});assert.equal(v(m).revenue,100);assert.equal(m.lastPlayerCard.machinery.lost,1);});
test('technology mandatory payment uses loans and fails on unknown funds without consuming the card',()=>{const s=tech();v(s).revenue=0;v(s).capital=0;const n=play(s,{qty:2,companyIds:['cc_shopping_mall_init','cc_clinic_init']});assert.equal(v(n).loans,1);assert.equal(v(n).capital,5);v(s).loans=null;const before=E.copy(s);assert.throws(()=>play(s,{qty:1,companyIds:['cc_shopping_mall_init']}),/未確認/);assert.deepEqual(s,before);});
