require('../dist/companies.js');
require('../dist/boards.js');
const E=require('../dist/engine.js'),{test}=require('node:test'),assert=require('node:assert/strict');
function setup(){return E.reduce(E.initial(),{type:'setup',players:2,immigrant:'',market:[],confirmed:true});}
function market(s){return WCA_COMPANIES.filter(d=>!d.tags.includes('Initial_Setup')&&['market','unbuilt'].includes(s.records.companies[d.id].status)).slice(0,4).map(d=>d.id);}

test('preparation preview follows Immigration and Foreign Trade policies',()=>{const s=setup();let p=WCARecords.preparationPreview(s.records,s.positions);assert.deepEqual({immigration:p.Working.immigrationCards,newWorkers:p.Working.newWorkers,deals:p.Capitalist.dealCards},{immigration:1,newWorkers:3,deals:1});s.positions[7]='C';s.positions[6]='C';p=WCARecords.preparationPreview(s.records,s.positions);assert.deepEqual({immigration:p.Working.immigrationCards,newWorkers:p.Working.newWorkers,deals:p.Capitalist.dealCards},{immigration:2,newWorkers:4,deals:2});});

test('preparation pays starting-loan interest, drops prosperity, adds workers, and replaces cards',()=>{const s=setup(),r=s.records,w=r.personal.Working.values,c=r.personal.Capitalist.values;w.cash=3;w.loans=1;w.prosperity=4;c.revenue=2;c.capital=0;c.loans=1;s.positions[7]='C';s.positions[6]='C';const ids=market(s),result=WCARecords.applyPreparation(r,s.positions,{market:ids,immigration:['Orange','Gray'],exportCard:'輸出A',businessDeals:['取引1','取引2']}),n=result.records,nw=n.personal.Working.values,nc=n.personal.Capitalist.values;assert.deepEqual({cash:nw.cash,loans:nw.loans,prosperity:nw.prosperity,workers:nw.workerCount,population:nw.population,gray:n.common.unemployed.Working.Gray,orange:n.common.unemployed.Working.Orange},{cash:48,loans:2,prosperity:3,workers:14,population:4,gray:4,orange:1});assert.deepEqual({revenue:nc.revenue,capital:nc.capital,loans:nc.loans},{revenue:0,capital:47,loans:2});assert.deepEqual(Object.entries(n.companies).filter(([id,x])=>x.status==='market').map(([id])=>id),ids);assert.deepEqual(n.trade,{exportCard:'輸出A',businessDeals:'取引1\n取引2'});assert.equal(w.cash,3);});

test('preparation pays State interest and automatically repays a loan when treasury remains above 50',()=>{const s=setup(),ids=market(s),state=s.records.personal.State.values;state.cash=61;state.loans=1;const preview=WCARecords.preparationPreview(s.records,s.positions);assert.deepEqual(preview.State,{interest:5,loansBefore:1,cashBefore:61,payoffs:1,loansAfter:0,cashAfter:6});const result=WCARecords.applyPreparation(s.records,s.positions,{market:ids,immigration:['Gray'],exportCard:'輸出',businessDeals:['取引']});assert.deepEqual({cash:result.records.personal.State.values.cash,loans:result.records.personal.State.values.loans},{cash:6,loans:0});});

test('preparation requires the exact immigration, market, export, and deal inputs',()=>{const s=setup(),ids=market(s);assert.throws(()=>WCARecords.applyPreparation(s.records,s.positions,{market:ids,immigration:[],exportCard:'輸出',businessDeals:['取引']}),/移民/);assert.throws(()=>WCARecords.applyPreparation(s.records,s.positions,{market:ids.slice(0,3),immigration:['Gray'],exportCard:'輸出',businessDeals:['取引']}),/企業市場/);assert.throws(()=>WCARecords.applyPreparation(s.records,s.positions,{market:ids,immigration:['Gray'],exportCard:'',businessDeals:['取引']}),/輸出カード/);});

test('completing preparation advances the round and restores eligible priority cards',()=>{let s=setup();s.phase='preparation';s.round=4;s.positions[7]='A';s.aside.actions.STR='strikeTokens';const ids=market(s);s=E.reduce(s,{type:'preparationApply',confirmed:true,plan:{market:ids,immigration:[],exportCard:'輸出',businessDeals:['取引']}});assert.equal(s.round,5);assert.equal(s.phase,'start');assert.equal(E.locate(s,'actions','STR'),0);assert.equal(s.aside.policies['7'],'finalRound');assert(s.lastPreparation);});

