require('../dist/companies.js');require('../dist/boards.js');
const E=require('../dist/engine.js'),{test}=require('node:test'),assert=require('node:assert/strict');
function setup(){return E.reduce(E.initial(),{type:'setup',players:2,immigrant:'',market:[],confirmed:true});}
function production(){const s=setup();s.turn=5;s.phase='player';return E.reduce(s,{type:'playerEnd'});}
function preparationPlan(s){return {market:WCA_COMPANIES.filter(d=>!d.tags.includes('Initial_Setup')&&['market','unbuilt'].includes(s.records.companies[d.id].status)).slice(0,4).map(d=>d.id),immigration:['Gray']};}
const trade=()=>({exportCard:{name:'export',offers:[{resource:'food',quantity:3,revenue:20}]},businessDeals:[{name:'deal',food:2,luxury:0,cost:15}]});

test('the fifth pair of turns enters Production and snapshots Labor Market policy',()=>{let s=production();assert.equal(s.phase,'production');assert.deepEqual(s.production,{step:'produce',laborPolicy:'B',wageDraws:[]});assert.equal(s.turn,5);});

test('production pays both Capitalist and State wages, produces stock, and clears commitments',()=>{let s=production();s.records.companies.cc_supermarket_init.slots[0].committed=true;s=E.reduce(s,{type:'productionProduce'});assert.equal(s.production.step,'needs');assert.equal(s.records.personal.Working.values.cash,110);assert.equal(s.records.personal.Capitalist.values.revenue,80);assert.equal(s.records.personal.State.values.cash,80);assert.equal(s.records.personal.Capitalist.values.food,5);assert.equal(s.records.personal.Capitalist.values.luxury,5);assert.equal(s.records.common.values.health,9);assert.equal(s.records.common.values.education,9);assert.equal(s.records.companies.cc_supermarket_init.slots[0].committed,false);});

test('Capitalist automa fills the Free Trade Zone, buys one Storage for 20, and stores the remainder',()=>{const s=E.reduce(E.initial(),{type:'setup',players:2,immigrant:'',market:[],automaClass:'Capitalist',confirmed:true}),cap=s.records.personal.Capitalist.values;Object.assign(cap,{food:8,freeTradeFood:7,foodStorage:0,revenue:120,capital:0});const result=WCARecords.applyProduction(s.records),after=result.records.personal.Capitalist.values,food=result.preview.storage.find(x=>x.resource==='food');assert.equal(after.freeTradeFood,8);assert.equal(after.foodStorage,1);assert.equal(after.food,11);assert.equal(food.boughtStorage,true);assert.equal(food.lost,0);assert.equal(after.revenue,60);});

test('Capitalist automa never buys a second Storage and loses only the excess',()=>{const s=E.reduce(E.initial(),{type:'setup',players:2,immigrant:'',market:[],automaClass:'Capitalist',confirmed:true}),cap=s.records.personal.Capitalist.values;Object.assign(cap,{food:16,freeTradeFood:8,foodStorage:1});const result=WCARecords.applyProduction(s.records),after=result.records.personal.Capitalist.values,food=result.preview.storage.find(x=>x.resource==='food');assert.equal(after.foodStorage,1);assert.equal(after.food,16);assert.equal(after.freeTradeFood,8);assert.equal(food.boughtStorage,false);assert.equal(food.lost,4);});

test('wage flows identify payer and recipient, including future Middle Class companies',()=>{let s=production(),r=s.records;r.participants.Middle='human';r.personal.Middle={values:{cash:50,population:1,workerCount:2,prosperity:0,loans:0,influence:0,vp:0,billMarkers:3,food:0,health:0,education:0,luxury:0},note:''};r.companies.cc_supermarket_init.slots.forEach(x=>x.owner='Middle');const id='mc_convenience_store_init',c=r.companies[id];c.status='built';c.operating='yes';c.wage='L2';c.slots[0].owner='Middle';c.slots[1].owner='Working';const preview=WCARecords.productionPreview(r),flows=preview.payments.map(x=>`${x.from}>${x.to}:${x.amount}`);assert(flows.includes('Capitalist>Middle:20'));assert(flows.includes('Middle>Working:8'));assert(flows.includes('State>Working:20'));s=E.reduce(s,{type:'productionProduce'});assert.equal(s.records.personal.Middle.values.cash,62);assert.equal(s.records.personal.Middle.values.food,3);assert.equal(s.records.personal.Working.values.cash,98);});

test('a level 2 strike skips production and wages, grants Influence, then is removed',()=>{let s=production(),c=s.records.companies.cc_supermarket_init;c.strike=true;s=E.reduce(s,{type:'productionProduce'});assert.equal(s.records.personal.Capitalist.values.food,1);assert.equal(s.records.personal.Capitalist.values.revenue,100);assert.equal(s.records.personal.Working.values.cash,90);assert.equal(s.records.personal.Working.values.influence,2);assert.equal(s.records.companies.cc_supermarket_init.strike,false);});

test('food needs transfer domestic payment and foreign tariff and use mandatory loans',()=>{let s=production();s=E.reduce(s,{type:'productionProduce'});s.records.personal.Working.values.cash=0;s=E.reduce(s,{type:'productionNeeds',plan:{capitalist:2,foreign:1}});assert.equal(s.records.production,undefined);assert.equal(s.records.personal.Working.values.cash,11);assert.equal(s.records.personal.Working.values.loans,1);assert.equal(s.records.personal.Capitalist.values.food,3);assert.equal(s.records.personal.Capitalist.values.revenue,104);assert.equal(s.records.personal.State.values.cash,85);assert.equal(s.production.step,'imf');});

test('IMF check repays enough State loans when affordable',()=>{let s=production();s=E.reduce(s,{type:'productionProduce'});s=E.reduce(s,{type:'productionNeeds',plan:{capitalist:3,foreign:0}});s.records.personal.State.values={...s.records.personal.State.values,cash:120,loans:2};s=E.reduce(s,{type:'productionImf'});assert.equal(s.records.personal.State.values.cash,10);assert.equal(s.records.personal.State.values.loans,0);assert.equal(s.production.step,'taxes');});

test('taxes use the production-start Labor policy, update both classes and State, then enter scoring',()=>{let s=production();s=E.reduce(s,{type:'productionProduce'});s=E.reduce(s,{type:'productionNeeds',plan:{capitalist:3,foreign:0}});s=E.reduce(s,{type:'productionImf'});const treasury=s.records.personal.State.values.cash,working=s.records.personal.Working.values.cash,cap=s.records.personal.Capitalist.values.revenue;s.positions[2]='A';s=E.reduce(s,{type:'productionTaxes'});assert.equal(s.phase,'scoring');assert.equal(s.records.personal.Working.values.cash,working-12);assert.equal(s.records.personal.Capitalist.values.revenue,cap-50);assert.equal(s.records.personal.State.values.cash,treasury+62);s=E.reduce(s,{type:'scoringApply'});assert.equal(s.phase,'preparation');s=E.reduce(s,{type:'preparationTrade',value:trade()});s=E.reduce(s,{type:'preparationApply',confirmed:true,plan:preparationPlan(s)});assert.equal(s.round,2);assert.equal(s.turn,1);assert.equal(s.phase,'start');});

test('food needs automatically buy from the cheapest source and prefer Foreign on a tie',()=>{const r=setup().records;r.personal.Working.values.population=5;r.personal.Working.values.food=1;r.personal.Capitalist.values.food=2;r.personal.Capitalist.values.foodPrice=8;assert.deepEqual(WCARecords.foodNeedPlan(r,'C'),{capitalist:2,foreign:2,total:36,reason:'資本家の安い在庫を使い、残りを海外市場から購入'});r.personal.Capitalist.values.foodPrice=10;assert.deepEqual(WCARecords.foodNeedPlan(r,'C'),{capitalist:0,foreign:4,total:40,reason:'同額のため海外市場を優先'});r.personal.Capitalist.values.foodPrice=12;assert.deepEqual(WCARecords.foodNeedPlan(r,'C'),{capitalist:0,foreign:4,total:40,reason:'海外市場の方が安い'});});
