const {chromium}=require(process.argv[2]),{pathToFileURL}=require('node:url'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await b.newPage({viewport:{width:390,height:844}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.resolve(__dirname,'../dist/index.html')).href);await p.locator('#setupWelcomeLater').click();
await p.locator('#tab-common').click();assert.equal(await p.locator('#companyPick option').count(),28);
await p.locator('#companyForm [name=status]').selectOption('built');await p.locator('#companyForm [name=wage]').selectOption('L2');await p.locator('[data-owner="0"]').selectOption('Working');await p.locator('[data-committed="0"]').check();await p.locator('#companyForm button[type=submit]').click();
await p.locator('#undo').click();assert.equal(await p.locator('#companyForm [name=status]').inputValue(),'unknown');
await p.locator('#companyForm [name=status]').selectOption('built');await p.locator('#companyForm [name=wage]').selectOption('L2');await p.locator('[data-owner="0"]').selectOption('Working');await p.locator('[data-committed="0"]').check();await p.locator('#companyForm button[type=submit]').click();
await p.locator('#companyPick').selectOption('cc_supermarket_pool');assert.equal(await p.locator('[data-owner="0"]').inputValue(),'unknown');await p.locator('#companyPick').selectOption('cc_supermarket_init');assert.equal(await p.locator('[data-committed="0"]').isChecked(),true);
await p.locator('#tab-personal').click();await p.locator('[data-number=cash]').fill('40');await p.locator('[data-number=population]').fill('5');await p.locator('[data-union=Food]').check();await p.locator('#personalForm button[type=submit]').click();
await p.reload();await p.locator('#tab-personal').click();assert.equal(await p.locator('[data-number=cash]').inputValue(),'40');assert.equal(await p.locator('[data-union=Food]').isChecked(),true);
await p.locator('[data-number=cash]').fill('50');p.once('dialog',d=>d.dismiss());await p.locator('#tab-common').click();assert.equal(await p.locator('#view-personal').isVisible(),true);await p.locator('#personalForm button[type=submit]').click();
await p.locator('#tab-common').click();assert.equal(await p.locator('[data-committed="0"]').isChecked(),true);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:path.resolve(__dirname,'../records-mobile-qa.png'),fullPage:true});
await p.setViewportSize({width:1254,height:828});await p.locator('#tab-personal').click();await p.screenshot({path:path.resolve(__dirname,'../records-desktop-qa.png'),fullPage:true});assert.deepEqual(errors,[]);console.log('PASS records tabs: 28 companies, same-name separation, workers and commitment, personal fields, undo, reload, unsaved input guard, responsive layout');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

