require('../dist/companies.js');require('../dist/boards.js');require('../dist/judge.js');require('../dist/capitalist.js');
const E=require('../dist/engine.js'),{test}=require('node:test'),assert=require('node:assert/strict');
function player(){return E.reduce(E.initial(),{type:'setup',players:2,automaClass:'Capitalist',confirmed:true,market:[]});}
const basic=(s,plan)=>E.reduce(s,{type:'workingBasic',plan});
test('Working purchase uses selected suppliers and allows one basic action per turn',()=>{let s=player();s.records.personal.Capitalist.values.health=3;s.records.personal.Capitalist.values.healthPrice=5;let before=E.copy(s.records);s=basic(s,{action:'BGS',resource:'health',purchases:[{source:'State',qty:2},{source:'Capitalist',qty:1}]});assert.equal(s.records.personal.Working.values.health,3);assert.equal(s.records.personal.Working.values.cash,before.personal.Working.values.cash-15);assert.equal(s.records.common.values.health,before.common.values.health-2);assert.equal(s.records.personal.Capitalist.values.health,before.personal.Capitalist.values.health-1);assert.equal(s.records.personal.Capitalist.values.revenue,before.personal.Capitalist.values.revenue+5);assert.throws(()=>basic(s,{action:'PRESSURE'}),/実行済み/);s=E.reduce(s,{type:'playerEnd'});assert.equal(s.phase,'start');assert.equal(s.workingBasicUsed,false);});
test('Working imports food at policy tariff and rejects excess quantity or unsupported sources atomically',()=>{let s=player();s.records.personal.Working.values.cash=100;const before=E.copy(s);const n=basic(s,{action:'BGS',resource:'food',purchases:[{source:'Foreign',qty:2}]});assert.equal(n.records.personal.Working.values.cash,70);assert.equal(n.records.personal.State.values.cash,s.records.personal.State.values.cash+10);assert.throws(()=>basic(s,{action:'BGS',resource:'food',purchases:[{source:'Foreign',qty:4}]}),/人口/);assert.throws(()=>basic(s,{action:'BGS',resource:'health',purchases:[{source:'Foreign',qty:1}]}),/購入先/);assert.deepEqual(s,before);});
test('Working assigns selected skills to a whole company and commits workers',()=>{let s=player(),id=Object.keys(s.records.companies).find(id=>s.records.companies[id].status==='built'&&s.records.companies[id].slots.every(x=>x.owner==='empty'));const c=s.records.companies[id],d=WCA_COMPANIES.find(d=>d.id===id),skills=c.slots.map((x,i)=>d.workers[i].type==='Skilled'?d.workers[i].color:'Gray');skills.forEach(skill=>s.records.common.unemployed.Working[skill]=3);const n=basic(s,{action:'AW',allocations:[{companyId:id,skills}]});assert.equal(n.records.companies[id].operating,'yes');assert.ok(n.records.companies[id].slots.every(x=>x.owner==='Working'&&x.committed));assert.throws(()=>basic(s,{action:'AW',allocations:[{companyId:id,skills:['Gray']}]}),/全スロット/);assert.throws(()=>basic(s,{action:'AW',allocations:[{companyId:id,skills:['Gray','Gray','Gray','Gray']}]}),/1〜3/);});
test('Working establishes a union only with four employed workers and the correct skilled unemployed worker',()=>{let s=player();assert.throws(()=>basic(s,{action:'AW',unions:['Food']}),/4人/);let count=0;for(const d of WCA_COMPANIES.filter(d=>d.industry==='Food'&&d.class==='Capitalist')){if(count>=4)break;const c=s.records.companies[d.id];c.status='built';c.slots.forEach(x=>{x.owner='Working';count++;});}s.records.common.unemployed.Working.Green=1;const before=WCARecords.workingWorkerCount(s.records),vp=s.records.personal.Working.values.vp,n=basic(s,{action:'AW',unions:['Food']});assert.equal(n.records.personal.Working.unions.Food,true);assert.equal(n.records.personal.Working.values.vp,vp+2);assert.equal(WCARecords.workingWorkerCount(n.records),before);});
test('Working strikes chosen eligible company and rejects committed workers and public companies',()=>{const s=player(),id='cc_supermarket_init',n=basic(s,{action:'STR',companyIds:[id]});assert.equal(n.records.companies[id].strike,true);assert.ok(n.records.companies[id].slots.every(x=>x.committed));s.records.companies[id].slots[0].committed=true;assert.throws(()=>basic(s,{action:'STR',companyIds:[id]}),/ストライキできない/);const publicId=Object.keys(s.records.companies).find(id=>s.records.companies[id].status==='built'&&[...WCA_COMPANIES,...WCA_EXTRA_COMPANIES].find(d=>d.id===id)?.class==='State'&&s.records.companies[id].slots.some(x=>x.owner==='Working'));assert.throws(()=>basic(s,{action:'STR',companyIds:[publicId]}),/ストライキできない/);});
test('Working pressure and demonstration use their own tokens and eligibility',()=>{let s=player();const n=basic(s,{action:'PRESSURE'});assert.equal(n.records.common.values.workingVotesOutside,14);assert.equal(n.records.common.values.capitalistVotesOutside,17);s.records.common.unemployed.Working.Gray=20;const d=basic(s,{action:'DEM'});assert.equal(d.records.common.tokens.demonstration,true);s.records.common.unemployed.Working.Gray=0;assert.throws(()=>basic(s,{action:'DEM'}),/デモには/);});
test('Working pending and immediate proposals use Working markers and return to player phase',()=>{let s=player();assert.throws(()=>E.reduce(s,{type:'workingPolicy',id:'1',position:'A'}),/隣接/);s=E.reduce(s,{type:'workingPolicy',id:'1',position:'B'});assert.equal(s.proposals['1'].proposer,'Working');assert.equal(s.records.personal.Working.values.billMarkers,2);s=player();s.records.personal.Working.values.influence=2;s=E.reduce(s,{type:'workingPolicy',id:'2',position:'A',immediate:true});assert.equal(s.phase,'election');assert.equal(s.election.queue[0].proposer,'Working');assert.equal(s.records.personal.Working.values.influence,1);assert.equal(s.workingBasicUsed,true);s=E.reduce(s,{type:'electionDeclare',sides:{Working:'favor',Capitalist:'against'},cubes:{Working:3,Capitalist:1,Middle:1}});s=E.reduce(s,{type:'electionResolve',spends:{Working:0},autoSymbols:{}});assert.equal(s.phase,'player');assert.equal(s.workingBasicUsed,true);assert.equal(s.positions['2'],'A');});
test('Working actions reject an automa turn and a Capitalist human turn',()=>{const s=player();s.phase='start';assert.throws(()=>basic(s,{action:'PRESSURE'}),/手番/);s.phase='player';s.automaClass='Working';assert.throws(()=>basic(s,{action:'PRESSURE'}),/手番/);});
